### ISSUE TITLE
Double semicolon before nesting crashes

### ISSUE THREAD

**Issue by ArnaudBarre** [parcel-bundler/lightningcss#111]
I'm still not sure if this a perfectly valid syntax, but I'm doing some pre-processing on the css before giving it parcel, and by simplicity I always add a `;` at the end of each rule, sometime resulting in two `;` .

Ie seems to works fine, expect when before a nesting selector: [playground](https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22safari%22%3A851968%7D%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20color%3A%20red%3B%3B%5Cn%20%20font-size%3A%2015px%3B%5Cn%5Cn%20%20%26.bar%20%7B%5Cn%20%20%20%20color%3A%20green%3B%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22unusedSymbols%22%3A%5B%5D%7D).

Feel free to close if this is not a supported syntax.

**Comment by sapphi-red** [comment]
It seems the crash doesn't happen in the latest version.

**Comment by ArnaudBarre** [comment]
You're everywhere 😄
Let's close it then!
