### ISSUE TITLE
Improper RTL code when using nesting

### ISSUE THREAD

**Issue by bakura10** [parcel-bundler/lightningcss#175]
Hi :),

Currently Parcel CSS generates invalid code when you are using nesting with logical properties.

This code:

```
.test {
  inset-inline-start: 50px;

  &:active {
    cursor: grabbing;
  }
}
```

Gives this:

```
.test:active {
  cursor: grabbing;
}

.test:active:not(:lang(ae), :lang(ar), :lang(arc), :lang(bcc), :lang(bqi), :lang(ckb), :lang(dv), :lang(fa), :lang(glk), :lang(he), :lang(ku), :lang(mzn), :lang(nqo), :lang(pnb), :lang(ps), :lang(sd), :lang(ug), :lang(ur), :lang(yi)) {
  left: 50px;
}

.test:active:-webkit-any(:lang(ae), :lang(ar), :lang(arc), :lang(bcc), :lang(bqi), :lang(ckb), :lang(dv), :lang(fa), :lang(glk), :lang(he), :lang(ku), :lang(mzn), :lang(nqo), :lang(pnb), :lang(ps), :lang(sd), :lang(ug), :lang(ur), :lang(yi)) {
  right: 50px;
}

.test:active:is(:lang(ae), :lang(ar), :lang(arc), :lang(bcc), :lang(bqi), :lang(ckb), :lang(dv), :lang(fa), :lang(glk), :lang(he), :lang(ku), :lang(mzn), :lang(nqo), :lang(pnb), :lang(ps), :lang(sd), :lang(ug), :lang(ur), :lang(yi)) {
  right: 50px;
}
```

As you can see ParcelCSS incorrectly generates the code with the nested selector.

**Comment by jamcow** [comment]
If it helps diagnose... choosing v1.7.4 or below [in the playground](https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22safari%22%3A589824%7D%2C%22source%22%3A%22.test%20%7B%5Cn%20%20inset-inline-start%3A%2050px%3B%5Cn%5Cn%20%20%26%3Aactive%20%7B%5Cn%20%20%20%20cursor%3A%20grabbing%3B%5Cn%20%20%20%20margin-inline-start%3A%200.7rem%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%221.7.4%22%7D) does generate 'correct' fallback code (also works with/without the nesting):
```
.test {
  left: var(--ltr, 50px);
  right: var(--rtl, 50px);
}

.test:active {
  cursor: grabbing;
  margin-left: var(--ltr, .7rem);
  margin-right: var(--rtl, .7rem);
}

[dir="ltr"] {
  --ltr: initial;
  --rtl: ;
}

[dir="rtl"] {
  --ltr: ;
  --rtl: initial;
}
```
