### ISSUE TITLE
Bettor error message when mixing nesting rules and declarations

### ISSUE THREAD

**Issue by ArnaudBarre** [parcel-bundler/lightningcss#253]
I'm trying to migrate from [postcss-nested](https://github.com/postcss/postcss-nested) to parcel-css when I discovered that in the spec, [we can't mix nesting rules and declarations](https://drafts.csswg.org/css-nesting-1/#mixing). But postcss-nested is very lenient about it, and is the [default one with tailwind](https://tailwindcss.com/docs/using-with-preprocessors#nesting)

The current error when doing this is `Unexpected end of input` ([playground](https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6815744%7D%2C%22source%22%3A%22.markdown%20%7B%5Cn%20%20color%3A%20blue%3B%5Cn%20%20%26%20a%20%7B%5Cn%20%20%20%20text-decoration%3A%20underline%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn.markdown2%20%7B%5Cn%20%20%26%20a%20%7B%5Cn%20%20%20%20text-decoration%3A%20underline%5Cn%20%20%7D%5Cn%20%20color%3A%20red%3B%5Cn%7D%5Cn%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)) which is a bit hard to understand when you don't about this limitation of the spec.

I think a specific error message in that case would help people migrate from postcss.

Thanks again for your work!

Side question: Is it out of scope to implement a more lenient version of nesting? (i.e. non madatory `&` and mixing rules/declarations) I understand why the spec adds this limitation, but I think this apply a lot less when using performant build time tools like parcel-css. And the same way nobody dropped babel when es6 was available everywhere, nobody will drop parcel-css or postcss when nesting is widely available.

**Comment by devongovett** [comment]
Sure, we can improve the error messages.

> Side question: Is it out of scope to implement a more lenient version of nesting?

Yes. I would like to keep Parcel CSS focused on standard spec-compliant CSS, and not venture into custom syntax. Ideally, once browsers support nesting natively, you won't even need to compile it.

**Comment by ArnaudBarre** [comment]
This is not an error anymore 🚀
