### ISSUE TITLE
How to use bundleAsync in Deno?

### ISSUE THREAD

**Issue by oscarotero** [parcel-bundler/lightningcss#277]
Hi, thanks for adding the new `bundleAsync` API to 1.14.0. It will be very useful to bundle CSS with custom resolvers.
Unfortunately, this function is not available in the CDN: https://unpkg.com/browse/lightningcss-wasm@1.14.0/index.js
Is there any way to import it in Deno?

**Comment by devongovett** [comment]
Unfortunately, it's not currently possible with the WASM build as the bundler relies heavily on napi and native multi-threading. Perhaps it's possible to do with WASM, but I'm not sure how... If anyone knows, please chime in.
