### ISSUE TITLE
CLI no longer works after upgrading to Lightning

### ISSUE THREAD

**Issue by bakura10** [parcel-bundler/lightningcss#282]
Hi,

Since upgrading to lightning, I am completely unable to make the CLI works. It must be something stupid but it has been 2 hours and I still can't find the reason. It seems the CLI is now exposed as a separate package (I think it should be added in the changelog), but despite also adding "lightnincss-cli" to my package.json, nothing is exported in the .bin folder:

<img width="207" alt="image" src="https://user-images.githubusercontent.com/1198915/189584243-9f18896f-4e75-4f86-b562-3088bffcf65e.png">

Previously, I had "parcel-css" in the list).

Is there an extra step I am missing here?

**Comment by carestad** [comment]
I am also not able to run either of the following `npx` commands, one of which is directly from the readme of the repo here:

- `npx lightningcss --help` (shows NPM error `could not determine executable to run`)
- `npx lightningcss-cli --help` (shows shell error `sh: 1: lightningcss: not found`)

Feels like this might be related

**Comment by devongovett** [comment]
Maybe the post install script is broken? Can you verify what packages are installed on your machine?

**Comment by bakura10** [comment]
Sure @devongovett . Here are the packages installed:

<img width="272" alt="image" src="https://user-images.githubusercontent.com/1198915/189785018-bccb5c71-30be-441b-809d-0cff80ee2439.png">

But for some reason the lightningcss binary is not properly copied into the bin folder.

**Comment by devongovett** [comment]
Hmm yeah I can see that. I don't quite understand why it's broken though. The postinstall script is correctly copying into `node_modules/lightningcss-cli/lightningcss`, and that executable runs. But npm/yarn just don't create the link in `node_modules/.bin` for some reason. As far as I can tell, the only thing that changed was the name...

**Comment by bakura10** [comment]
I'm not sure if that help, but with ParcelCSS I just needed one dependency (ParcelCSS exclusively) and it installed also the CLI. Here, I actually needed to add an extra package. So it seems there was maybe something more than just the name?

**Comment by devongovett** [comment]
hmm no, Parcel CSS had the cli in `@parcel/css-cli`, and the node bindings in `@parcel/css`.

**Comment by devongovett** [comment]
Oh I think maybe it's that this file wasn't renamed: https://github.com/parcel-bundler/lightningcss/blob/master/cli/parcel_css

**Comment by devongovett** [comment]
Should be fixed in v1.15.0.
