### ISSUE TITLE
Parcel performs incorrect CSS optimization

### ISSUE THREAD

**Issue by lazex** [parcel-bundler/lightningcss#283]
```css
div {
  flex: 1 1 0;
}
```

is converted to

```css
div {
  flex: 1;
}
```

These are different.

Example is here.

```html
<!DOCTYPE html>

<style>
	.box {
		display: inline-flex;
		flex-direction: column;
		width: 100px;
		min-height: 100px;
		border: 1px solid silver;
	}
	.container {
		overflow: auto;
	}
	.case1 {
		flex: 1 1 0;
	}
	.case2 {
		flex: 1;
	}
	.large {
		height: 200px;
		background: yellow;
	}
</style>

<div class="box">
	<div>1</div>
	<div class="container case1">
		<div class="large">large</div>
	</div>
</div>

<div class="box">
	<div>2</div>
	<div class="container case2">
		<div class="large">large</div>
	</div>
</div>
```

![notitle](https://user-images.githubusercontent.com/6133978/189895472-9e694060-8251-4312-a140-81c51418cd0f.png)

**Comment by devongovett** [comment]
hmm, the spec says:

> ''flex: [<number [1,∞]>](https://drafts.csswg.org/css-values-4/#number-value)''
Equivalent to ''flex: [<number [1,∞]>](https://drafts.csswg.org/css-values-4/#number-value) 1 0''. Makes the flex item flexible and sets the [flex basis](https://drafts.csswg.org/css-flexbox/#flex-flex-basis) to zero, resulting in an item that receives the specified proportion of the free space in the flex container. If all items in the flex container use this pattern, their sizes will be proportional to the specified flex factor.

https://drafts.csswg.org/css-flexbox/#flex-common

Browsers seem to be treating a `flex-basis` of `0%` and `0` differently, and treating `flex: 1` as `flex 1 0 0%`. I don't see where this is specified though?

**Comment by devongovett** [comment]
Seems that it was changed in the spec but browsers haven't implemented it yet: https://github.com/w3c/csswg-drafts/issues/5742

Example browser bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1368592

**Comment by lazex** [comment]
Thank you for your prompt response.
