### ISSUE TITLE
How should minify be used from Rust?

### ISSUE THREAD

**Issue by edimoldovan** [parcel-bundler/lightningcss#297]
I have been trying to minify the output with Rust. There's a code snippet which I tried with, taken from here https://docs.rs/lightningcss/1.0.0-alpha.34/lightningcss/stylesheet/struct.StyleSheet.html

```
let fs = FileProvider::new();
let mut bundler = Bundler::new(&fs, None, ParserOptions::default());
let stylesheet = bundler.bundle(Path::new("./assets/css/global.css")).unwrap();
stylesheet.minify(MinifyOptions::default());
println!("{}", stylesheet.to_css(PrinterOptions::default()).unwrap().code);
```

The printed CSS is not minified so I'm assuming that minify use is incorrect. If I try to print the out of the minify call, I seem to be getting nothing, or specifically `"()"`

**Comment by devongovett** [comment]
There are two parts to minification: structural changes (e.g. merging rules, combining properties, etc.), and syntax (e.g. removing whitespace). `stylesheet.minify()` does the first part (among other things - it should really be renamed to `transform`). The second part is done by the printer. So you need:

```rust
stylesheet.to_css(PrinterOptions {
  minify: true,
  ..PrinterOptions::default()
})
```
