### ISSUE TITLE
should not transform color transparent to #0000 when Chrome > 60

### ISSUE THREAD

**Issue by tjx666** [parcel-bundler/lightningcss#299]
reproduce steps:

1. `git clone git@github.com:tjx666/webpack-css-minify-issue.git`
2. `git checkout lightningcss`
3. `pnpm install`
4. `pnpm run build`
5. open `dist/main.css`
6. you can see the color is minify to hex'

Right behavior:
1. `git checkout master`
2. change webpack config to use default minifier intead of lightningcss
3. change targets version to `Chrome > 60` in `package.json`
4. `pnpm run build`
5. the color `transparent` will not be tansformed to hex

**Comment by devongovett** [comment]
Seems to work in the [playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A3932160%7D%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20color%3A%20transparent%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D).

I think this is a config issue. `Chrome` should be lowercase `chrome`: https://github.com/tjx666/webpack-css-minify-issue/blob/300a4a452f311bc51fa8ae68604dc34919ce4ccf/webpack.config.js#L32

**Comment by devongovett** [comment]
actually, `browserslistToTargets` returns a full target object, not just chrome, so it really should be:

```js
targets: css.browserslistToTargets(browserslist('Chrome > 60'))
```
