### ISSUE TITLE
@parcel/transformer-css: Invalid pseudo class after pseudo element

### ISSUE THREAD

**Issue by midnightgamer** [parcel-bundler/lightningcss#305]
I am trying to setup parcel with a bootstrap project and when I am trying to build the project, I am getting this error for following code 

`after:empty{display:none}
`

**Comment by devongovett** [comment]
yup, that's invalid. pseudo classes other than user actions (e.g. `:active`, `:hover`) cannot be applied to pseudo elements. you need to swap the order so empty comes before after.

https://www.w3.org/TR/selectors-4/#pseudo-element-states
