### ISSUE TITLE
modify (prepend) class names?

### ISSUE THREAD

**Issue by horacimacias** [parcel-bundler/lightningcss#316]
I'm trying to modify a css file programmatically, to prepend some fixed string to every class defined in the css file, if possible using rust.
I've been looking at the documentation/api but can't seem to find a way to do this; does this crate provide a way to do this?
If so, can somebody please point me to an example or documentation?

**Comment by devongovett** [comment]
It's not really possible to do custom transforms on selectors at the moment. You can, however, use the CSS modules features to accomplish this specific case. Something like this:

```rust
use lightningcss::stylesheet::{StyleSheet, ParserOptions, PrinterOptions, css_modules};

let mut stylesheet = StyleSheet::parse("...", ParserOptions {
  css_modules: Some(css_modules::Config {
    css_modules::Pattern::parse("my-prefix-[local]")?,
  }),
  ..ParserOptions::default()
})?;

let res = stylesheet.to_css(PrinterOptions::default())?;
println!("{}", res.code);
```

Note that this affects more than just classes, however. Id selectors, CSS variables, keyframes, etc. will also be renamed with this approach.

**Comment by horacimacias** [comment]
thanks! let me give this a go and see if it works for me.
