### ISSUE TITLE
bundle doesn't output the @import dependencies

### ISSUE THREAD

**Issue by lili21** [parcel-bundler/lightningcss#318]
with the option `analyzeDependencies: true`, run `css.bundle` doesn't output the `@import` dependencies

**Comment by alexnozer** [comment]
Yes, I've encountered the same issue. I want to use the asynchronous `bundleAsync` function, but when I use it with `analyzeDependencies: true` flag, it returns an empty dependencies array that I want to use. When I use the synchronous function `transform` function, the dependencies array is populated. Why doesn't it work for `bundle` and `bundleAsync`?

**Comment by devongovett** [comment]
That's because after bundling there are no more dependencies (they've been bundled into the output).
