### ISSUE TITLE
Implement ToCss to PseudoElement

### ISSUE THREAD

**Issue by whizsid** [parcel-bundler/lightningcss#329]
I am implementing a CSS minifier with my custom logics. Using the crates from this repository to parse my code and minify. I am using that kind of code to minify.
```rust
match component {
       // Other match arms that using lightningcss::traits::ToCss
       _=>{
             // Using cssparser::ToCss as a fallback for other match arms
             write!(&mut component_str, "{}", component.to_css_string()).unwrap();
       }
}
```
This code gave me an error. Because PseudoElement is throwing an `unreachable!()` error when converting to string. Then I tried to use the `ToCss` trait from lightningcss crate. But the exposed [parcel_selectors::parser::PseudoElement](https://docs.rs/parcel_selectors/0.24.7/parcel_selectors/parser/trait.PseudoElement.html) trait not implemented to the `lightningcss::traits::ToCss`. Is there any existing workaround to fix it. If not can you implement ToCss to PseudoElement?

**Comment by devongovett** [comment]
It does implement `lightningcss::traits::ToCss`:

https://github.com/parcel-bundler/lightningcss/blob/1eccce556606ce80956c744e82d23d2405072358/src/selector.rs#L744

**Comment by whizsid** [comment]
@devongovett Yes. But unfortunately `selector.rs` module is private.
https://github.com/parcel-bundler/lightningcss/blob/1eccce556606ce80956c744e82d23d2405072358/src/lib.rs#L34
So those PseudoElement, Selectors, PseudoClass types can not access from outside.

**Comment by devongovett** [comment]
The `selector` module is exposed in #94.
