### ISSUE TITLE
`compat.rs`: Media query interval syntax incorrectly marked as globally unsupported

### ISSUE THREAD

**Issue by LeoniePhiline** [parcel-bundler/lightningcss#331]
# Range vs interval syntax

Reading the above sources, it appears to me as if browsers make no difference between range (`(width < 500px)`) and interval (`(200px <= width < 500px)`) syntax, following [CSS Media Queries 4](https://www.w3.org/TR/mediaqueries-4/#mq-range-context) while lightningcss treats range syntax as supported and interval syntax as (incorrectly) unsupported.

# Supported by various browser distribs:

- Can I Use: https://caniuse.com/css-media-range-syntax
- MDN Compat: https://developer.mozilla.org/en-US/docs/Web/CSS/@media#browser_compatibility under "**Range syntax from Media Queries Level 4**"
- Compat data available: https://github.com/mdn/browser-compat-data/blob/main/css/at-rules/media.json#L1304-L1341 

# Marked as globally unsupported:

- `compat.rs` (generated): https://github.com/parcel-bundler/lightningcss/blob/master/src/compat.rs#L1211-L1213
- Hard-coded global incompatibility in generator: https://github.com/parcel-bundler/lightningcss/blob/1eccce556606ce80956c744e82d23d2405072358/scripts/build-prefixes.js#L229

# Interval syntax demo

https://jsfiddle.net/cwmefnq9/

**Comment by devongovett** [comment]
Looks like this was fixed in be440efe8feeaab7351cf3a27d58a1f062bcabf0
