### ISSUE TITLE
Can I replace postcss with lightingcss?

### ISSUE THREAD

**Issue by GiveMe-A-Name** [parcel-bundler/lightningcss#336]
Hi, I recently became interested in the lightningcss tools. It seems to be a faster and more compressed alternative to postcss in webpack's css processing. But there may be many plugins or even custom plugins in postcss. Is there a similar plugin mechanism in lightningcss that allows users to extend the functionality?

Or, to put it another way, can Lightning be used as an alternative to postcss?

**Comment by devongovett** [comment]
At the moment, custom plugins are not supported. But, if you are only using a few very common plugins, such as autoprefixer, postcss-preset-env, postcss-nesting, postcss-modules, etc. that are covered by lightningcss, then you may be able to ditch postcss entirely. Even removing these from your postcss config and using lightningcss and postcss together can improve performance.

**Comment by GiveMe-A-Name** [comment]
got it. Thanks for your respond.

**Comment by devongovett** [comment]
Custom plugins are now supported in the latest release! See https://lightningcss.dev/transforms.html

**Comment by GiveMe-A-Name** [comment]
That's so great that we can write some custom plugin to extend `lightingcss` abilities.
Good!
