### ISSUE TITLE
A plugin for vite?

### ISSUE THREAD

**Issue by surajondev** [parcel-bundler/lightningcss#339]
Hey,

I am trying to build an application with Vite and Lightning CSS. I am finding it challenging to integrate Lightning CSS as there is no guide.

Can you please guide me on this?

Thanks in advance for your response.

**Comment by devongovett** [comment]
There is https://github.com/lawrencecchen/vite-plugin-lightningcss but it only replaces postcss for transforming modern css to older browsers. Vite has hard coded postcss into the core for other things like collecting dependencies and bundling, and uses ESBuild for minification. Those cannot currently be replaced by plugins. I'd suggest opening a Vite issue for lightningcss support!

**Comment by surajondev** [comment]
Okay. Thanks will look into this.

**Comment by meduzen** [comment]
Follow-up Vite issue: https://github.com/vitejs/vite/issues/11029

**Comment by devongovett** [comment]
Lightning CSS is now built into Vite. Closing.
