### ISSUE TITLE
':global/:local(.className)' adds space before className

### ISSUE THREAD

**Issue by klimashkin** [parcel-bundler/lightningcss#344]
When using [lightningcss-loader](https://github.com/fz6m/lightningcss-loader) in `webpack.config.js` before `css-loader` with CSS Modules, then `:global/local()` selectors on the lightning step adds a space between `.` and `className`, which breaks `css-loader`

Valid `:global/:local` selectors:
https://github.com/css-modules/css-modules#exceptions

Example:
https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.a%20%7B%5Cn%20%20%26%20%3Aglobal(.globclass)%20%7B%5Cn%20%20%20%20%26%20b%20%7B%5Cn%20%20%20%20%20%20color%3A%20green%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn.localA%20%3Aglobal%20.global-b%20.global-c%20%3Alocal(.localD.localE)%20.global-d%20%7B%5Cn%20%20color%3A%20orange%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/576077/204197494-7422ae86-3133-4e56-8194-c01e54e44f76.png">

**Comment by devongovett** [comment]
Fixed by 6a2adb6
