### ISSUE TITLE
Does it supports @import <url | path>?

### ISSUE THREAD

**Issue by aelbore** [parcel-bundler/lightningcss#346]
Thanks for this really awesome library, i been using this for some of my projects 👍 
Just wondering does this support @import <url | path>? correct me if im wrong as of now we cannot transform it by file we need to read the file then transform the string.

**Comment by devongovett** [comment]
Not sure I understand the question. Could you clarify or give an example?

**Comment by aelbore** [comment]
apologies, i just saw in readme it supports `@import` and path resolver
this is what i mean for example

shared.css
```
.no-margin-padding {
  padding: 0;
  margin: 0;
}
```


styles.css
```
@import "./shared.css"

:host {
  h1 {
    color: red
   }
}

```

**Comment by devongovett** [comment]
Ok sounds like you answered the question.
