### ISSUE TITLE
Error when parsing some edge cases for new nesting syntax

### ISSUE THREAD

**Issue by bakura10** [parcel-bundler/lightningcss#348]
Hi,

I am trying to migrate our code to remove the @nest, but a few cases throw an error:

Valid:

```
.input, .textarea, .select {
  @nest label + & {
    color: red;
  }
}
```

Invalid:

```
.input, .textarea, .select {
  label + & {
    color: red;
  }
}
```

Error: Unexpected token Delim('+')

[Playground URL](https://lightningcss.dev/playground#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.input%2C%20.textarea%2C%20.select%20%7B%5Cn%20%20label%20%2B%20%26%20%7B%5Cn%20%20%20%20color%3A%20red%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

**Comment by devongovett** [comment]
Nested selectors cannot start with an element selector, because it's ambiguous with a property. See https://drafts.csswg.org/css-nesting/#syntax.

You can do this:

```css

.input, .textarea, .select {
  :is(label) + & {
    color: red;
  }
}
```

**Comment by bakura10** [comment]
Thanks, this does the trick :)

**Comment by mischnic** [comment]
The [minified output](https://lightningcss.dev/playground#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.foo%7B%5Cn%20%20%3Ais(label)%20%2B%20%26%20%7B%5Cn%20%20%20%20color%3A%20red%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D) is `:is(label)+.foo{color:red}` though, I think the first `:is` can be removed? (Which seems useful if `:is` has to be used to workaround the syntax). So related to https://github.com/parcel-bundler/lightningcss/commit/b870d1fcbb7db44147eae1274150ab81394b281b

And furthermore, `:is(label)+.foo{color:red}` is not getting transpiled to `-webkit-any` [if the targets don't support it](https://lightningcss.dev/playground#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A5242880%7D%2C%22source%22%3A%22%3Ais(label)%2B.foo%7Bcolor%3Ared%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)?
