### ISSUE TITLE
More flexible settings for "pseudoClasses"

### ISSUE THREAD

**Issue by anwerso** [parcel-bundler/lightningcss#350]
Usually polyfills do not patch native implementations. So ruleset need to be cloned, not just replaced pseudo class selector, For example something like this:
```
.form:focus-within label {
  color: lime;
}
```

transforms to 

```
.form.focus-within label {
  color: lime;
}
.form:focus-within label {
  color: lime;
}
```

Also, some polyfills use an attribute selector (`[focus-within]`) which you cannot use in the current state. But this is a minor inconvenience, unlike rulesets cloning.

The idea is to add more options to the `pseudoClasses`, but I can understand if it is not in the priority list.

**Comment by devongovett** [comment]
I think the custom transform API (#363) should be able to solve that case!

**Comment by devongovett** [comment]
The custom transform API is now released. See https://lightningcss.dev/transforms.html
