### ISSUE TITLE
Examples of using Lightning CSS in Node

### ISSUE THREAD

**Issue by surajondev** [parcel-bundler/lightningcss#359]
I am not able to implement lightning CSS in Node. I might be missing something. So, do you have an example of using lightning CSS in Node with a complete codebase?

Please let me know if you have anything like this.

**Comment by devongovett** [comment]
Have you looked at the documentation? What are you missing? https://github.com/parcel-bundler/lightningcss#from-node

**Comment by surajondev** [comment]
I tried it but couldn't able to implement those into my code. So, do you have a full project example?

**Comment by mischnic** [comment]
1. Create a new folder
2. run `yarn add lightningcss`
3. Copy the example from https://github.com/parcel-bundler/lightningcss#from-node into a new file `index.js`
4. Run `node index.js`

Again: what problem are you running into?

**Comment by surajondev** [comment]
Okay. How the webpage will be rendered with the above example?

**Comment by devongovett** [comment]
Building a whole webpage is beyond the scope of lightningcss. For that, you will want a full build tool like [Parcel](https://parceljs.org), which uses lightningcss under the hood.

**Comment by surajondev** [comment]
So, that means using nodejs alone will not create a webpage that supports lightning CSS's minified version?

**Comment by surajondev** [comment]
Also after minifying the CSS the code is just a buffer. How I can use it?
