### ISSUE TITLE
SyntaxError: Unexpected token Colon

### ISSUE THREAD

**Issue by Semigradsky** [parcel-bundler/lightningcss#362]
I get the error `SyntaxError: Unexpected token Colon` when tried to minify the Foundation CSS file: https://cdnjs.cloudflare.com/ajax/libs/foundation/6.7.5/css/foundation.css

Other minifiers (`clean-css`, `cssnano`, `csso`, `esbuild`) not failed.

**Comment by devongovett** [comment]
This file contains invalid CSS:

```css
@media screen and (min-width: 0\0) {}
```

**Comment by Semigradsky** [comment]
Ah I see, it is a hack for detecting IE - http://browserbu.gs/css-hacks/media-min-width-0-backslash-0/

**Comment by devongovett** [comment]
If you run with the `errorRecovery` option, it should skip invalid rules.
