### ISSUE TITLE
A keyword for plugin authors similar to `postcss-plugin`

### ISSUE THREAD

**Issue by romainmenke** [parcel-bundler/lightningcss#364]
If you want to find a PostCSS plugin on npm you would filter by [`postcss-plugin`](https://www.npmjs.com/search?q=keywords:postcss-plugin).
It would be interesting to pick a keyword for lightningcss plugins.
Something like `lightningcss-plugin`.

If this is well documented more people will do this and make it easier for others to find existing plugins.

**Comment by devongovett** [comment]
Yeah still need to figure out how plugin packages are structured and loaded. Right now I have just been working on the visitor API for the node api, and will probably initially release it as an experimental feature to get API feedback. If you have any ideas or feedback based on your experience with postcss plugins, I'd love to hear it btw!

**Comment by devongovett** [comment]
The custom transform API is now released. I added a keyword to the example in the docs about how to publish a plugin. https://lightningcss.dev/transforms.html#publishing-a-plugin
