### ISSUE TITLE
Space is added when non-minified

### ISSUE THREAD

**Issue by bakura10** [parcel-bundler/lightningcss#368]
Hi :),

When using the non-minify mode, Lightning generates invalid CSS.

The following code:

```
.foo {
  font-size: var(--text-font-size-min)px;
}
```

is transformed to:

```
.foo {
  font-size: var(--text-font-size-min) px;
}
```

However, the value `1px` is valid while `1 px` is not.

Can be reproduced [in playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20font-size%3A%20var(--text-font-size-min)px%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

Thanks :)

**Comment by devongovett** [comment]
Variables don't concatenate like strings. These are parsed as two separate tokens, not one dimension token, regardless of whether there is a space. If you try your first example in a browser, you can see that it doesn't work as you expected.

**Comment by bakura10** [comment]
Interesting, I did not know that. Then, this means the minify mode has a bug. In minify mode, there is [no space](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20font-size%3A%20var(--text-font-size-min)px%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D).

So one mode or the other has a problem ;)

**Comment by bakura10** [comment]
Never mind, I think I get it now.
