### ISSUE TITLE
Visitor for unknown at rule is only working when nesting is enabled

### ISSUE THREAD

**Issue by ArnaudBarre** [parcel-bundler/lightningcss#384]
Reproduction:
```js
import { transform } from "lightningcss";

transform({
  filename: "index.css",
  code: Buffer.from(`.foo {
  @apply h-full;
}
`),
  // drafts: { nesting: true },
  visitor: {
    Rule: {
      unknown: (rule) => {
        console.log(rule);
      },
    },
  },
});
```

[playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20%40apply%20h-full%3B%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Atrue%2C%22visitor%22%3A%22%7B%20%5Cn%20%20Rule%3A%20%7B%5Cn%20%20%20%20unknown%3A%20(rule)%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20console.log(rule)%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

Is this an expected behaviour?

**Comment by devongovett** [comment]
Yes because your source code contains a nested rule which can only be parsed when nesting is enabled.
