### ISSUE TITLE
Support :nth-child(An+B of S) selector

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/lightningcss#392]
https://twitter.com/bramus/status/1612755458774929408?s=46&t=lpI6XmtY372a72fvrYjzGg

**Comment by yisibl** [comment]
Yes, we need this selector.

When implementing it, we need to take care of the whitespace after `of`. https://github.com/w3c/csswg-drafts/issues/8285

**Comment by bakura10** [comment]
This is now supported on Chrome and Firefox, would be awesome to have this supported :).

**Comment by bakura10** [comment]
@devongovett , is there a known workaround for that? For now I am managing a separate stylesheet to just have those selectors that is not managed by Lighting, but this makes maintenance a bit harder :(.

**Comment by devongovett** [comment]
Implemented in the above commit.
