### ISSUE TITLE
Custom unit transform get a InvalidArg  Error 

### ISSUE THREAD

**Issue by noyobo** [parcel-bundler/lightningcss#393]
```
$ bun ./test.ts
1 | import { Token, transform } from 'lightningcss';
2 | import { Selector, Declaration, Function } from 'lightningcss/node/ast';
3 |
4 | const css = `.a {width: 12rpx}`;
5 |
6 | const result = transform({
                   ^
InvalidArg: data did not match any variant of untagged enum ValueOrVec
```

playground: <https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6946816%7D%2C%22source%22%3A%22.a%20%7Bheight%3A%20100rpx%3B%7D%22%2C%22visitorEnabled%22%3Atrue%2C%22visitor%22%3A%22%7B%5Cn%20%20Token(path)%20%7B%5Cn%20%20%20%20%20%20if%20(path.type%20%3D%3D%3D%20'dimension')%20%7B%5Cn%20%20%20%20%20%20%20%20return%20%7B%20type%3A%20'dimension'%2C%20value%3A%20100%20*%202%2C%20unit%3A%20'px'%20%7D%3B%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D>

**Comment by devongovett** [comment]
The return type of the Token visitor is a `TokenOrValue` object, so you need to set `type: 'token'`:

```js
return {type: 'token', value: { type: 'dimension', value: 100 * 2, unit: 'px' }};
```

[Example](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6946816%7D%2C%22source%22%3A%22.a%20%7Bheight%3A%20100rpx%3B%7D%22%2C%22visitorEnabled%22%3Atrue%2C%22visitor%22%3A%22%7B%5Cn%20%20Token(path)%20%7B%5Cn%20%20%20%20%20%20if%20(path.type%20%3D%3D%3D%20'dimension')%20%7B%5Cn%20%20%20%20%20%20%20%20return%20%7Btype%3A%20'token'%2C%20value%3A%20%7B%20type%3A%20'dimension'%2C%20value%3A%20100%20*%202%2C%20unit%3A%20'px'%20%7D%7D%3B%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

Alternatively, you could return a length there:

```js
return {type: 'length', value: {value: 100 * 2, unit: 'px' }};
```

[Example](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6946816%7D%2C%22source%22%3A%22.a%20%7Bheight%3A%20100rpx%3B%7D%22%2C%22visitorEnabled%22%3Atrue%2C%22visitor%22%3A%22%7B%5Cn%20%20Token(path)%20%7B%5Cn%20%20%20%20%20%20if%20(path.type%20%3D%3D%3D%20'dimension')%20%7B%5Cn%20%20%20%20%20%20%20%20return%20%7Btype%3A%20'length'%2C%20value%3A%20%7Bvalue%3A%20100%20*%202%2C%20unit%3A%20'px'%20%7D%7D%3B%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

At some point I plan to incorporate TypeScript into the playground so you get better errors.

**Comment by noyobo** [comment]
Thank you for your answer.
But I think such a design is not very friendly, and the structure of input and output is inconsistent, which leads to more understanding costs.

```js
{
  Token(path) {
    return path;  // same error
  }
}
```

babel like this:

```js
import * as parser from "@babel/parser";
import traverse from "@babel/traverse";

const code = `function square(n) {
  return n * n;
}`;

const ast = parser.parse(code);

traverse(ast, {
  enter(path) {
    if (path.isIdentifier({ name: "n" })) {
      path.node.name = "x";
    }
  },
});
```

or postcss: 

```js
const plugin = () => {
  return {
    postcssPlugin: 'to-red',
    Rule (rule) {
      console.log(rule.toString())
    },
    Declaration (decl) {
      console.log(decl.toString())
      decl.value = 'red'
    }
  }
}
plugin.postcss = true

await postcss([plugin]).process('a { color: black }', { from })
// => a { color: black }
// => color: black
// => a { color: red }
// => color: red
```

**Comment by noyobo** [comment]
> Yeah the reason is so you can replace the node with a value of a different type. If you could only replace tokens with other tokens (and not other types of values like lengths or colors) it would be quite limiting, for example.

Get!
