### ISSUE TITLE
Custom transform API truncates custom property name

### ISSUE THREAD

**Issue by stevenpetryk** [parcel-bundler/lightningcss#399]
Hey there, just a tiny surprise when using the new visitor API. My use case is this:

```diff
.foo {
- color: opacity($black, 0.5);
+ color: hsl(var(--black-hsl) / 0.5);
}
```

But I noticed that LightningCSS was transforming to:

```css
.foo {
  color: hsl(var(--ack-hsl) / 0.5);
}
```

A small reproduction shows that the `ident` passed to any `var` gets its first two characters chopped off. 

[Playground link ↗️](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20background%3A%20opacity(%24abcdef)%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Atrue%2C%22visitor%22%3A%22%7B%5Cn%20%20Function(fn)%20%7B%5Cn%20%20%20%20const%20varName%20%3D%20fn.arguments%5B1%5D.value.value%3B%5Cn%5Cn%20%20%20%20fn.arguments%20%3D%20%5B%5Cn%20%20%20%20%20%20%7B%20%5Cn%20%20%20%20%20%20%20%20type%3A%20'var'%2C%20%5Cn%20%20%20%20%20%20%20%20value%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20name%3A%20%7B%20ident%3A%20varName%20%7D%2C%20%5Cn%20%20%20%20%20%20%20%20%20%20fallback%3A%20null%2C%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%5D%5Cn%20%20%20%20%5Cn%20%20%20%20return%20%7B%5Cn%20%20%20%20%20%20type%3A%20'function'%2C%5Cn%20%20%20%20%20%20value%3A%20fn%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

Of course, fixing was as easy as prefixing the `ident` with two characters, but that doesn't seem right.

**Comment by devongovett** [comment]
Variable names should include the leading `--` when you return them, so try prepending that to your `varName`. [Example](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20background%3A%20opacity(%24abcdef)%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Atrue%2C%22visitor%22%3A%22%7B%5Cn%20%20Function(fn)%20%7B%5Cn%20%20%20%20const%20varName%20%3D%20fn.arguments%5B1%5D.value.value%3B%5Cn%5Cn%20%20%20%20fn.arguments%20%3D%20%5B%5Cn%20%20%20%20%20%20%7B%20%5Cn%20%20%20%20%20%20%20%20type%3A%20'var'%2C%20%5Cn%20%20%20%20%20%20%20%20value%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20name%3A%20%7B%20ident%3A%20'--'%20%2B%20varName%20%7D%2C%20%5Cn%20%20%20%20%20%20%20%20%20%20fallback%3A%20null%2C%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%5D%5Cn%20%20%20%20%5Cn%20%20%20%20return%20%7B%5Cn%20%20%20%20%20%20type%3A%20'function'%2C%5Cn%20%20%20%20%20%20value%3A%20fn%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

**Comment by stevenpetryk** [comment]
Yeah, it makes sense that the `--` is included—but since custom property names always begin with `--` (I think?), perhaps it'd be valuable to warn/panic when trying to print a custom property with an invalid ident, rather than silently replacing the first two characters.

**Comment by stevenpetryk** [comment]
(What I'm getting at here is that the silent replacement is the surprising/footgun part, not the "idents should start with --" part)

**Comment by devongovett** [comment]
Yep, I can add an error
