### ISSUE TITLE
How to handle invalid CSS values

### ISSUE THREAD

**Issue by vladinator1000** [parcel-bundler/lightningcss#427]
HI folks, should lightningcss throw an error when you pass it invalid CSS like this one?

```css
.corrupt {
  color: hsla(120, 62.32%;
}
```

I was hoping this to throw so that I can use lightningcss to validate a dynamic CSS input at runtime.

[Playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.corrupt%20%7B%5Cn%20%20color%3A%20hsla(120%2C%2062.32%25%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D )

For example, when browsers encounter this they error:
![image](https://user-images.githubusercontent.com/1226564/226948310-1c8e2708-6a15-418a-876b-69ea677d1766.png)

**Comment by vladinator1000** [comment]
Hi @devongovett, I started working on a fix for this. Managed to create a test case for it here https://github.com/parcel-bundler/lightningcss/pull/449/files#diff-c85a5adfc0fdc9027536b06beaeef70a871e7cc6f67f030d09816d883d0630a7R8

Do you have any recommendations on how I could approach the implementation? I'm new to the codebase ❤️

**Comment by devongovett** [comment]
Thanks. I think there's a specific error code that we need to handle when parsing custom properties ([here](https://github.com/parcel-bundler/lightningcss/blob/master/src/properties/custom.rs#L296)). Certain token types are considered errors including `CloseParenthesis`, `CloseSquareBracket`, etc. (see [here](https://github.com/servo/rust-cssparser/blob/master/src/tokenizer.rs#L151-L177)). So I think we'd just want to error whenever we see one of those token types.
