### ISSUE TITLE
removing colon from pseudo elements

### ISSUE THREAD

**Issue by aryzen0001** [parcel-bundler/lightningcss#441]
Im using parcel and whenever I build the project for some reason its removing the colon from pseudo elements.
For example *::before becomes :before and p::before becomes p:before.

**Comment by devongovett** [comment]
Those are equivalent. How is this causing a problem for you?

**Comment by aryzen0001** [comment]
Oh im new to css and didnt know that. Also, I asked on stackoverflow and they said it wasnt equivalent. Can you explain how they are equivalent?

**Comment by vsapsai** [comment]
MDN [mentions](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements)
> Double colons (::) are used for pseudo-elements. This distinguishes pseudo-elements from [pseudo-classes](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes) that use single colon (:) in their notation.

The problem is that when only a single colon is used, browsers don't apply corresponding CSS rule.
