### ISSUE TITLE
View Transition pseudo-elements with pseudo-class marked as invalid

### ISSUE THREAD

**Issue by chriskirknielsen** [parcel-bundler/lightningcss#443]
Hi there,

I've started playing around with the View Transition API, which allows selectors that are a little novel, such as `::view-transition-group:has(::view-transition-new(*):only-child)`.

However, when trying to run minification on my styles, an error is thrown:
> Invalid pseudo class after pseudo element, only user action pseudo classes (e.g. :hover, :active) are allowed (via SyntaxError)

Here is a [simple demo](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A7274496%7D%2C%22source%22%3A%22%3A%3Aview-transition-new(*)%3Aonly-child%20%7B%5Cn%5Ctanimation-duration%3A%20500ms%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D) to reproduce it:
```css
::view-transition-new(*):only-child {
	animation-duration: 500ms;
}
```

The parser would seem to need new logic to allow pseudo-classes attached to pseudo-elements as this is now a valid use-case.

Thank you!

**Comment by nuttycom** [comment]
I'm seeing similar issues with the `:disabled` pseudo-class (https://developer.mozilla.org/en-US/docs/Web/CSS/:disabled)
