### ISSUE TITLE
Parcel crashes with some use of nested calc/variables

### ISSUE THREAD

**Issue by danielearwicker** [parcel-bundler/lightningcss#444]
# 🐛 bug report

Crash, silently on Windows, SIGBUS on macOS but no other details.

## 💻 Code Sample

Clone, `yarn`, `yarn start`, it crashes: https://github.com/danielearwicker/parcel-crash-repro

## 🌍 Your Environment

Have tried macOS 13.1, Windows 10, and also this occurs with parcel (2.8.3) and 2.0.0-nightly.1254

**Comment by jacobrask** [comment]
It’s invalid css though, `3` doesn’t mean anything here. Should give a better error but the input wouldn’t work in a browser either.

`height: calc(3rem - calc(0.5rem - 2px));` works

**Comment by amurashinffdc** [comment]
It also crashes with a unitless `0`, which is a valid value.

**Comment by sapphi-red** [comment]
This seems to be already fixed by e3c8e12f989651c51d3ae430d888bee7eb058207 and 378955ed60e88b00791b08c32d9e6d39bea7a4c6.
