### ISSUE TITLE
Fails to parse when there is new line before value

### ISSUE THREAD

**Issue by chinchang** [parcel-bundler/lightningcss#447]
Eg:

```
dt {
 clip-path: 
   path('m0 0v75q70-6 75-75m54 150q71-60 141 0');
}
```

This is valid CSS for browser. But lightningcss parses it as:

```
dt {
 clip-path: ;
}
```

**Comment by devongovett** [comment]
Seems to work in the [playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22dt%20%7B%5Cn%20clip-path%3A%20%5Cn%20%20%20path('m0%200v75q70-6%2075-75m54%20150q71-60%20141%200')%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D).

Where are you seeing this problem?
