### ISSUE TITLE
Inner custom at-rules and functions seem to be evaluated after outer functions

### ISSUE THREAD

**Issue by riskygit** [parcel-bundler/lightningcss#452]
Custom at-rule to be used by a visitor: `@red: #f00;`
```
.test {
  color: color-mix(in srgb, @red 50%, #ef323d 50%);
}
```
Result: `.test{color:color-mix(in srgb,red 50%,#ef323d 50%)}`

This should have been evaluated further.

**Comment by devongovett** [comment]
That is not a location where an at rule is valid syntax. In CSS, at rules are only allowed in rule lists (i.e. as a sibling to `.test`), not inside functions.
