### ISSUE TITLE
How to use stylesheet with String

### ISSUE THREAD

**Issue by lmtr0** [parcel-bundler/lightningcss#470]
Hello there, 
I'm using the visitor api for a project, and I've tried to use the following code, however I get a compilation error.
My code basically uses the visitor api to count some things and do some modifications, but it's not shared across threads or anything else. I call the function with the arguments, expect the result, and we are done with it. How can I pass a string into it and not receive the compilation error?
```rust

// counts the number of elements in a css sheet and returns a minified version of it
pub fn my_func() -> anyhow::Result<String>{
    let data = data.clone();

    let res
    let count;
    {
        let mut sheet = StyleSheet::parse(
            &data,
            ParserOptions {
                filename: "<inline-file>".to_string(),
                ..ParserOptions::default()
            },
        )
        .context("Failed to create stylesheet")?;

        // let mut sheet = StyleSheet::parse(&data, ParserOptions::default())?;
        let mut visitor = WfVisitor::default();

        sheet.visit(&mut visitor)?;

        let result = sheet.to_css(PrinterOptions { minify: true, ..Default::default() })?;
        res = result.code.clone();
        count = visitor.count;

        drop(visitor);
        drop(sheet);
    }
    Ok((res, count))
}

```
```
error[E0597]: `data` does not live long enough
   --> Source/init/src/css.rs:107:13
    |
    |           let mut sheet = StyleSheet::parse(
    |  _________________________-
    | |             &data,
    | |             ^^^^^ borrowed value does not live long enough
    | |             ParserOptions {
    | |                 filename: "<inline-file>".to_string(),
...   |
    | |         )
    | |         .context("Failed to craate stylesheet");
    | |_______________________________________________- argument requires that `data` is borrowed for `'static`
...
    |   }
    |   - `data` dropped here while still borrowed
```

**Comment by lmtr0** [comment]
This is my current solution:
```rust
    let res;
    let data= Box::leak(data.into_boxed_str());

    let mut sheet = StyleSheet::parse(
        data,
        ParserOptions {
            filename: "<inline-file>".to_string(),
            css_modules: None,
            ..ParserOptions::default()
        },
    )
    .context("Failed to create stylesheet")?;

    // let mut sheet = StyleSheet::parse(&data, ParserOptions::default())?;
    let mut visitor = WfVisitor::default();

    sheet.visit(&mut visitor)?;

    let result = sheet.to_css(PrinterOptions { minify: false, ..Default::default() })?;
    res = result.code.clone();

    drop(sheet);
    drop(visitor);
```
I think I can do better, and I also think that this will eventually generate a memory leak

**Comment by devongovett** [comment]
I think the problem is that `anyhow::Result` has a bound of `Display + Send + Sync + 'static` on the `Context` trait. Both StyleSheet and ParseError borrow from the input string. Normally this isn't an issue because you don't keep the stylesheets or errors around longer than the input. But in this case, you're returning the result as an `anyhow::Result` rather than a regular `Result`, and that type erases the lifetime.

At the moment there's no "owned" error type available in lightningcss. In the meantime, you could do something like this if your code doesn't need any of the error details and a string would suffice.

```rust
StyleSheet::parse(
  // ...
)
.map_err(|err| anyhow::anyhow!("{:?}", err))
.context("Failed to create stylesheet")?;
```

The `map_err` formats the error to a string and returns that instead.

**Comment by lmtr0** [comment]
Ah, I didn't think about that. Thank you very much. It worked

**Comment by devongovett** [comment]
Great, glad it worked. I also just implemented an `into_owned` function for parser errors in the above commit, which will return a copy of the error that no longer borrows from the input (and therefore has a static lifetime). That'll be under the "into_owned" feature flag in the next release.

**Comment by lmtr0** [comment]
Sounds great, thx
