### ISSUE TITLE
`--custom-media` equivanelt in `vite` plugin options?

### ISSUE THREAD

**Issue by o-az** [parcel-bundler/lightningcss#474]
I first used `lightningcss-cli`, which worked:

```sh
lightningcss \
  --minify \
  --bundle \
  --custom-media \
  --nesting \
  index.css \
  --output-file out/index.css
```
Now how can I pass the same options in the `vite` plugin? `customMedia`, `nesting` and a few others [don't appear to be an option](https://github.com/parcel-bundler/lightningcss/blob/6e5d7148b60a566f605c96cad1a607fb67727bae/node/index.d.ts#L10-L67).

```ts
lightningcss({
	minify: true,
	targets: '>= 0.25%',
	//?? bundle: true,
	//?? customMedia: true,
	//?? nesting: true,
})
```

**Comment by devongovett** [comment]
customMedia and nesting go in the `drafts` option.

```js
lightningcss({
  drafts: {
    nesting: true
  }
});
```

`bundle` probably isn't supported by the vite plugin because vite doesn't allow overriding the css bundler yet. see https://github.com/vitejs/vite/issues/11029
