### ISSUE TITLE
Percentage containing a float

### ISSUE THREAD

**Issue by SinnerAir** [parcel-bundler/lightningcss#484]
The problem appears when a `Visitor` with processing is specified `style`.

Error: cannot serialize tagged newtype variant TextSizeAdjust::Percentage containing a float

Version package: 1.20.0

```
import { transform } from 'lightningcss';

transform({
  filename: '',
  code: Buffer.from(`html {
    text-size-adjust: 100%
  }`),
  visitor: {
    Rule: {
        style(rule) {
            return rule;
        }
    }
}
});
```

**Comment by marklawlor** [comment]
Can confirm, having a `Rule` visitor will cause `text-size-adjust` to fail. While `text-size-adjust` may not be a common rule to write, its often in CSS resets (such as TailwindCSS's `@base`).

**Comment by enjoyma** [comment]
Anyone fix it? `Rule` visitor are very common. @devongovett
