### ISSUE TITLE
Nesting option does output nested CSS

### ISSUE THREAD

**Issue by cedeber** [parcel-bundler/lightningcss#487]
When I run `lightningcss --nesting --bundle --minify --targets 'last 1 year' styles/styles.css -o out/assets/styles.css`, it output nested css.
With `last 2 years` it works. I am a bit confused what happened in the background here.

You can find an example that fails here: https://github.com/cedeber/korros-ui/blob/f6440ef367e68278bd25866870854d48a9254305/styles/trigger_button.css

**Comment by phoenix-ru** [comment]
AFAIK, CSS nesting is not supported enough: https://caniuse.com/css-nesting. But the fact that it is somewhat supported starting from Chrome 112 (which was released on April 4th 2023) probably causes the behaviour you are observing.

**Comment by devongovett** [comment]
Looks like this is due to an out of date version of browserslist. "last 1 year" was returning no browsers.
