### ISSUE TITLE
Merge exception for the same property under multiple same selectors

### ISSUE THREAD

**Issue by itmanyong** [parcel-bundler/lightningcss#498]
1. As shown in the figure below, is this the expected result
![image](https://github.com/parcel-bundler/lightningcss/assets/53500371/3100e01b-b70b-421c-a2df-2f7d00fe7f90)

2. The results expected by human thinking are as follows
```css
.view{color:#00f}
```

**Comment by devongovett** [comment]
For color this is fixed in the latest release.
