### ISSUE TITLE
Does this package work in Node.js worker threads?

### ISSUE THREAD

**Issue by JoshuaWise** [parcel-bundler/lightningcss#501]
The Node.js docs for [worker threads](https://nodejs.org/api/worker_threads.html#class-worker) states:
> Native add-ons can only be loaded from multiple threads if they fulfill [certain conditions](https://nodejs.org/api/addons.html#worker-support).

Does this package fulfill those conditions?

Edit: Another question: does this package take advantage of multithreading automatically?

**Comment by devongovett** [comment]
It should, yes. We run lightningcss from worker threads in Parcel.

> Another question: does this package take advantage of multithreading automatically?

The `transform` API is single threaded. `bundle` automatically parallelizes work for each file that is bundled.

**Comment by JoshuaWise** [comment]
One more question: Do [custom visitors](https://lightningcss.dev/transforms.html) work with `bundle`? If so, how does synchronization work when multiple threads are being used for bundling?

**Comment by devongovett** [comment]
The part that is parallelized is the parsing and resolving of each file. Custom transforms run afterward over the combined AST, single theaded.

**Comment by JoshuaWise** [comment]
Thanks!
