### ISSUE TITLE
CSS rules order getting messed up

### ISSUE THREAD

**Issue by cyberalien** [parcel-bundler/lightningcss#504]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

Basic empty project, no plugins, no config files, no dependencies other than `parcel`:

```json
{
  "name": "parcel-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "parcel src/index.html",
    "build": "parcel build src/index.html --public-url ."
  },
  "keywords": [],
  "author": "Vjacheslav Trushkin",
  "license": "ISC",
  "devDependencies": {
    "parcel": "^2.9.1"
  }
}
```

Test HTML file: `src/index.html`:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style>
      .test-icon {
        width: 1em;
        height: 1em;
        --svg: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='24' height='24'%3E%3Cpath fill='black' d='M2 3h2v18H2zm18 0h2v18h-2zM5 13h2v1h2v-1h2v1h2v-1h4v1h2v-4h-2v1h-4v-1h-2v1H9v-1H7v1H5zm0-9v4h2V7h8v1h2V7h2V5h-2V4h-2v1H7V4zm0 13v3h2v-1h2v1h2v-1h8v-2h-8v-1H9v1H7v-1H5z'/%3E%3C/svg%3E");
        background-color: currentColor;
        display: inline-block;
        -webkit-mask: none center / 100% no-repeat;
        mask: none center / 100% no-repeat;
        -webkit-mask-image: var(--svg);
        mask-image: var(--svg);
      }
    </style>
  </head>
  <body>
    <div>
      <span class="test-icon"></span>
    </div>
  </body>
</html>
```

## 🤔 Expected Behavior

Expected output CSS to be the same

## 😯 Current Behavior

`dist/index.html` contents:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>.test-icon {
  width: 1em;
  height: 1em;
  --svg: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='24' height='24'%3E%3Cpath fill='black' d='M2 3h2v18H2zm18 0h2v18h-2zM5 13h2v1h2v-1h2v1h2v-1h4v1h2v-4h-2v1h-4v-1h-2v1H9v-1H7v1H5zm0-9v4h2V7h8v1h2V7h2V5h-2V4h-2v1H7V4zm0 13v3h2v-1h2v1h2v-1h8v-2h-8v-1H9v1H7v-1H5z'/%3E%3C/svg%3E");
  -webkit-mask-image: var(--svg);
  -webkit-mask-image: var(--svg);
  mask-image: var(--svg);
  background-color: currentColor;
  display: inline-block;
  -webkit-mask: none center / 100% no-repeat;
  mask: none center / 100% no-repeat;
}

</style>
  </head>
  <body>
    <div>
      <span class="test-icon"></span>
    </div>
  <script src="/parcel-test.59712999.js"></script></body>
</html>

```

Notice different order of rules in CSS.

In original CSS order is:
1. mask
2. mask-image

In generated CSS order is:
1. mask-image
2. mask

This results in wrong CSS because `mask` overwrites `mask-image`, therefore `.test-icon` has no mask image.

## 💁 Possible Solution

Do not sort CSS rules.

**Comment by markgaze** [comment]
@devongovett this seems to be happening with other properties too, another [minimal repro](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20height%3A%20100%25%3B%5Cn%20%20height%3A%20var(--height)%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D) with the `height` property.

I know this code should probably be `height: var(--height, 100%);` but it's in a 3rd party package that we're consuming, unfortunately.

I can raise another issue, if that's a better way of reporting this so just let me know 🙂
