### ISSUE TITLE
Pseudo-Classing Psudeo-Elements Raising a False Invalid State

### ISSUE THREAD

**Issue by paguilera** [parcel-bundler/lightningcss#505]
Trying to update parcel to 2.9.1 and I'm getting `@parcel/transformer-css: Invalid state` This looks to be related to #149 which was the main result when I was searching for a solution, but in this instance, it looks like a valid syntax is falsely raising this issue.

I'm using `.foo::after:not(.bar)`.

Following the linked spec in #149 and scrolling up to [pseudo-element-states](https://www.w3.org/TR/selectors-4/#pseudo-element-states), I'm seeing:

> Clarify that [:not()](https://www.w3.org/TR/selectors-4/#negation-pseudo) and [:is()](https://www.w3.org/TR/selectors-4/#matches-pseudo) can be used when containing above-mentioned pseudos.

**Comment by devongovett** [comment]
Pretty sure this doesn't work in any browser https://codepen.io/devongovett/pen/BaGaZaW

**Comment by paguilera** [comment]
Thanks for the feedback. I'm checking with the rest of the dev team here to see how it got into our code base, was tested, etc.
