### ISSUE TITLE
Bug: No source locations in errors when using `bundleAsync()`

### ISSUE THREAD

**Issue by JoshuaWise** [parcel-bundler/lightningcss#507]
Hi, I want to use `bundleAsync` with a custom resolver, but I want to display nice error messages if either `resolver.read` or `resolver.resolve` throw an error (or return a rejected Promise). But I don't currently see any way to get the source location of the `@import` rule being processed. Even if I just let the error bubble up, `lightningcss` just throws `Error: GenericFailure, Promise rejected` with no other information. Is there something I'm missing?

**Comment by JoshuaWise** [comment]
I just realized, even if there's a syntax error in the CSS, the errors thrown by `lightningcss` just don't have any source location info. That makes this library kind of unusable for my purposes, which is too bad because I got really excited about replacing PostCSS. What are the chances source locations can be added to errors?

**Comment by devongovett** [comment]
It's there. See the `loc` and `fileName` properties of the error object. https://github.com/parcel-bundler/lightningcss/blob/11f4179f81041e14a04536d3bb0618f06de4e454/node/src/lib.rs#L1010

**Comment by JoshuaWise** [comment]
It doesn't appear to be working as intended. I can reproduce the issue with this simple script:

```js
'use strict';
const { bundleAsync } = require('lightningcss');

(async function main() {
	try {
		await bundleAsync({
			filename: 'style.css',
			minify: true,
			sourceMap: true,
		});
		console.log('No error!');
	} catch (err) {
		console.log(`Error: ${err.message}`);
		console.log(`Properties: ${Object.getOwnPropertyNames(err).join(', ')}`);
		console.log(`fileName: ${err.filename}`);
		console.log(`loc: ${err.loc}`);
	}
})();
```

With this `style.css` file:

```css
.foo {
	-webkit-flex 1; /* this line has a syntax error */
	flex: 1;
}
```

I get the following logs:

```
Error: Unexpected token Number { has_sign: false, value: 1.0, int_value: Some(1) }
Properties: stack, message, code
fileName: undefined
loc: undefined
```

**Comment by JoshuaWise** [comment]
FWIW, I'm using Node.js v18.13.0, and lightningcss v1.21.0

**Comment by devongovett** [comment]
Hmm bundleAsync may be an exception. I'll have to look into it
