### ISSUE TITLE
Selectors including `::marker` are split when Safari target is used 

### ISSUE THREAD

**Issue by RobinMalfait** [parcel-bundler/lightningcss#508]
I think there might be a bug when using `::marker`. Currently when you use `::maker` pseudo elements in a selector, the selector is split up the moment you add Safari to the list of targets (no matter what version you use of Safari).

According to the browser compatibility table on MDN (https://developer.mozilla.org/en-US/docs/Web/CSS/::marker#browser_compatibility), the `::marker` pseudo element has been supported in Safari since version 11.1. They also mention that it is only supported for `font-size` and `color` properties. But trying this out in the browser, adding other properties doesn't seem to break the selector at all.

Input:
```css
.foo,
.foo ::marker,
.foo::marker {
   color: red;
 }
```

Expected output:
```css
.foo, .foo ::marker, .foo::marker {
  color: red;
}
```

Actual output:
```css
.foo {
  color: red;
}

.foo ::marker {
  color: red;
}

.foo::marker {
  color: red;
}
```

You can see this behaviour in the playground:

1. With `Safari` as one of the targets: https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6750208%2C%22firefox%22%3A6684672%2C%22safari%22%3A917504%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.foo%2C%5Cn.foo%20%3A%3Amarker%2C%5Cn.foo%3A%3Amarker%20%7B%5Cn%20%20%20color%3A%20red%3B%5Cn%20%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D
2. Without `Safari` as one of the targets: https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6750208%2C%22firefox%22%3A6684672%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.foo%2C%5Cn.foo%20%3A%3Amarker%2C%5Cn.foo%3A%3Amarker%20%7B%5Cn%20%20%20color%3A%20red%3B%5Cn%20%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D

**Comment by devongovett** [comment]
oh hmm, I suspect it's due to being marked as partial support in the mdn data. I guess we can add an override.
