### ISSUE TITLE
Adding `Safari 15`, inserts `::-webkit-backdrop`

### ISSUE THREAD

**Issue by RobinMalfait** [parcel-bundler/lightningcss#511]
When you add Safari 15 or lower as one of the targets, then the rules for `::backdrop` are are vendor prefixed with `::-webkit-backdrop`.

Input:
```css
::backdrop {
  color: red;
}
```

Expected output:
```css
::backdrop {
  color: red;
}
```

Actual output:
```css
::-webkit-backdrop {
  color: red;
}

::backdrop {
  color: red;
}
```

E.g.: https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22safari%22%3A983040%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%3A%3Abackdrop%20%7B%5Cn%20%20color%3A%20red%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D

While this isn't the end of the world, it does increase the bundle size with CSS that I don't think is used. I can't seem to find any resources where Safari ever used the `-webkit-` prefix for `::backdrop`.

While testing this on an older MacBook with Safari 14 installed, it seems like both `::backdrop` and `::-webkit-backdrop` are both not working, making this additional CSS unnecessary. (The `dialog` element itself was also not working yet, and I had to enable the dialog element as one of the experimental features from the Develop menu)

I couldn't immediately find information in the codebase where this is coming from, so my gut says that this is coming from the caniuse-lite data. I wonder if something similar to your recent change (https://github.com/parcel-bundler/lightningcss/commit/cff779d78a7ea9639ed4c28059c19567d4814e0b) could be applied by marking this as an edge case as well?

**Comment by devongovett** [comment]
Hmm, looks like autoprefixer does the same. We use their data for all the prefixes, and looks like they get their data in turn from caniuse-lite. Looks like it was added in https://github.com/postcss/autoprefixer/issues/487.

**Comment by yisibl** [comment]
I'll fix the Autoprefixer issue here: https://github.com/browserslist/caniuse-lite/pull/116

**Comment by RobinMalfait** [comment]
👋 testing this again it looks like the changes @yisibl linked to solved this issue and this is no longer an actual issue.

Clicking the shared reproduction link from above doesn't include the `-webkit-` variant anymore. Going to close this issue for you 👍
