### ISSUE TITLE
Be forgiving for semicolons (`;`) on selector blocks

### ISSUE THREAD

**Issue by egilsster** [parcel-bundler/lightningcss#533]
Stumbled on this when trying to switch to LightningCSS for CSS minification. Not sure how feasible it is to make this change but it would be great if the processor/minifier would not fail completely on something so minutiae since `CssMinimizerPlugin` on it's own is able to handle it OK.

Here's a little [playground example ](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.my-css%20%7B%5Cn%20%20max-height%3A%2050%25%3B%5Cn%7D%3B%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D) that showcases it.

**Comment by silverwind** [comment]
What do browsers do? Accept or ignore such a block?

**Comment by egilsster** [comment]
Tried Firefox, Chrome, and Safari just now, they all just seem to ignore it and work fine if the CSS contains these extra semicolons, does not appear to mean anything to those browsers.

As for the minifier, I wouldn't expect it to choke on such characters whilst the CSS is perfectly valid otherwise.

**Comment by devongovett** [comment]
Browsers ignore anything that's invalid, including entire rules. But as a build tool, I think by default lightningcss should error when it comes across something invalid so that the developer can fix the problem. However, you can change this to a warning by enabling the `errorRecovery` option.

**Comment by egilsster** [comment]
I totally agree with you on showing a warning so devs can fix the issues. I am glad there's an option to get over this hurdle. Can keep that on until the fix reaches me. Thanks!
