### ISSUE TITLE
Lightning 1.21 generates invalid CSS for Webkit pseudo-selectors

### ISSUE THREAD

**Issue by bakura10** [parcel-bundler/lightningcss#536]
Hi !

Starting from Lightning 1.21, the following code:

```
.quantity-selector__input {
  appearance: textfield;

  &::-webkit-outer-spin-button,
  &::-webkit-inner-spin-button {
    -webkit-appearance: none;
    margin: 0;
  }
}
```

Generate as:

```
.quantity-selector__input {
  appearance: textfield;
}

:is(.quantity-selector__input::-webkit-outer-spin-button, .quantity-selector__input::-webkit-inner-spin-button) {
  -webkit-appearance: none;
  margin: 0;
}
```

Unfortunately the :is generates invalid code as the Webkit pseudo selectors do not work. Lightning 1.20 and lower generates the correct CSS (I am actually unsure as to why Lightning generates this as the first place, as this actually makes the code longer than what it has to be):

```
.quantity-selector__input {
  appearance: textfield;
}

.quantity-selector__input::-webkit-outer-spin-button, .quantity-selector__input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}
```

This is probably related to this: https://github.com/parcel-bundler/lightningcss/issues/352

If this is not a valid selector, then Lightning should generate something in the console, as this is a breaking change compared to the 1.20 and lower behavior :). This can caught by surprise everyone who upgrade to 1.21.

Thanks!

**Comment by bakura10** [comment]
@devongovett Unfortunately I figured out the issue is a bit more problematic, as even without nesting, Lightning CSS now generates invalid CSS. This:

```
.quantity-selector__input::-webkit-outer-spin-button,
.quantity-selector__input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}
```

Is also rewritten as this:

```
:is(.quantity-selector__input::-webkit-outer-spin-button, .quantity-selector__input::-webkit-inner-spin-button) {
  -webkit-appearance: none;
  margin: 0;
}
```

The only solution I see is making sure to rewrite like this, but of course this force to duplicate all the rules:

```
.quantity-selector__input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

.quantity-selector__input::-webkit-outer-spin-button {
  -webkit-appearance: none;
  margin: 0;
}
```

This also break a lot of places in my code base so for now I don't feel super confident upgrading to the latest version. I really think that showing should be done to prevent the rewrite to :is, at least not in this situation, as rewriting with :is actually generates longer output.

**Comment by MilllerTime** [comment]
Just hit this issue after upgrading Parcel in a project. Splitting each selector apart (not combining with a comma) is a workaround, but not ideal.

[`:is` does not select pseudo elements by design](https://developer.mozilla.org/en-US/docs/Web/CSS/:is#is_does_not_select_pseudo-elements), so rewriting code containing `::-webkit-outer-spin-button` etc to wrap them with `:is` simply breaks the code. It would be awesome if Lightning was aware of this CSS rule.

**Comment by calebdwilliams** [comment]
FWIW, we are having this issue at Slack and are trying to optimize our CSS performance and have this same issue. #1231 would have resolved this as well.
