### ISSUE TITLE
@media screen and (min-width: 0\0 )

### ISSUE THREAD

**Issue by guoyunhe** [parcel-bundler/lightningcss#542]
Fusion Design's CSS has some IE9 tricks (I don't know how and why):

https://github.com/alibaba-fusion/next/blob/f2f27fc2e1395e8d61a3415d3faab330d7c00275/src/grid/main.scss#L91

And lightningcss will throw errors on this.

**Comment by devongovett** [comment]
You could try the `errorRecovery` option, which will ignore rules with invalid syntax: https://lightningcss.dev/docs.html#error-recovery

**Comment by wszgrcy** [comment]
https://github.com/foundation/foundation-sites/blob/337be7a8d9d20d28f5d27d2d98131a6d3772506c/dist/css/foundation.css#L569
Same mistake
