### ISSUE TITLE
Add `:host-context` to TSPseudoClass

### ISSUE THREAD

**Issue by riskygit** [parcel-bundler/lightningcss#545]
`:host` is recognized, but `:host-context` is not. https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context.

**Comment by riskygit** [comment]
Any chance of this coming in a future update? I need to make a visitor for `:host-context(...)`.

**Comment by devongovett** [comment]
Hmm, looking through the link you posted it seems that this is a non-standard Chrome-only selector. According to the linked Firefox issue in the compatibility table, neither Mozilla nor Apple plan on implementing it and it will likely be removed from the spec. See https://github.com/w3c/csswg-drafts/issues/1914. Therefore I'm hesitant to implement it as well. It should already be parsed as `PsuedoClass::CustomFunction`. Does that work for you?

**Comment by Oriblish** [comment]
Yes

**Comment by riskygit** [comment]
It's workable... the main issue is the lack of specificity with the arguments. The `:host` type has `selectors`, but `custom-function`'s `arguments` are `TokenOrValue[]` where a class, for example, is a `delim` and an `ident`... so you can see how this is unraveling.

**Comment by riskygit** [comment]
@Oriblish how did you implement this?

**Comment by riskygit** [comment]
Tried messing with this more today... no luck, really. I'm basically left to parse the tokens into selector components, but this library already has that capability unexposed (as far as I'm aware). There's no "raw" component type that would just insert a string; even "type" escapes invalid type characters.

**Comment by riskygit** [comment]
Navigated the issue entirely by avoiding the need for a visitor on this selector.
