### ISSUE TITLE
`@starting-style` support

### ISSUE THREAD

**Issue by mayank99** [parcel-bundler/lightningcss#549]
The [`@starting-style` rule](https://drafts.csswg.org/css-transitions-2/#defining-before-change-style-the-starting-style-rule) is shipping in [chrome 117](https://chromestatus.com/feature/4515377717968896).

Currently it does not get unnested properly in lightningcss. Parsing fails with "Unknown at rule" and the selector gets dropped in the output. See [playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A7536640%2C%22firefox%22%3A7208960%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22div%20%7B%5Cn%20%20transition%3A%20background-color%200.5s%3B%5Cn%20%20background-color%3A%20transparent%3B%5Cn%5Cn%20%20%40starting-style%20%7B%5Cn%20%20%20%20background-color%3A%20yellow%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cnspan%20%7B%5Cn%20%20.foo%20%7B%5Cn%20%20%20%20transition%3A%20background-color%200.5s%3B%5Cn%20%20%20%20background-color%3A%20transparent%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D).

**Comment by devongovett** [comment]
Already implemented in eff8ce1a4e585c12b6ee888d8c6a351bca88cb8f just needs to be released

**Comment by mayank99** [comment]
ooh interesting. does the "local" version in the playground not use the latest commit?

**Comment by devongovett** [comment]
It would if you built the website locally, but right now there is no automatic deploy when pushing to the main branch

**Comment by devongovett** [comment]
Going to close since this is done, just needs to be released.
