### ISSUE TITLE
No ``lightningcss-linux-arm-musl`` target

### ISSUE THREAD

**Issue by ferferga** [parcel-bundler/lightningcss#563]
This make all projects that use LightningCSS inside ``node:18-alpine`` for the ``linux/arm`` platform fail since Alpine doesn't have glibc

**Comment by devongovett** [comment]
There's https://www.npmjs.com/package/lightningcss-linux-arm64-musl. Are you sure you're on a 32-bit arm?

**Comment by ferferga** [comment]
@devongovett Check this: https://github.com/jellyfin/jellyfin-vue/actions/runs/5882072278/job/15951827659#step:9:480

As you can see in the attached commits to this PR, switching to node:18 (which uses bookworm instead of Alpine under the hood) fixes the issue, as Alpine doesn't have glibc.

As you can see, linux/arm64 was built perfectly in the CI of my project, it's `linux/arm` that fails

**Comment by devongovett** [comment]
It probably just means you need to regenerate your lock file. You can do `rm -rf node_modules package-lock.json` and then run `npm install` again to rebuild it.

**Comment by ferferga** [comment]
@devongovett I already tried, without any luck, but that doesn't change anything as the target doesn't exist.

It's not even listed as a dependency in npm: https://www.npmjs.com/package/lightningcss?activeTab=dependencies

**Comment by devongovett** [comment]
Is there a strong reason to use 32-bit arm rather than 64?

**Comment by ferferga** [comment]
@devongovett Personally, none. A bit of context in our situation:

- In the past, we built our client in Linux amd64 and then copied the built assets to Dockere images for all platforms. However, reports of us breaking building in other platforms were recurring, so we decided to build in CI all the images in the target platform.
- There are many Raspberry Pi users around (me included) who still didn't upgrade to a 64-bit OS (I did, that's why I say I personally don't care), so I'd say 32-bit (at least in arm space) it's quite common. It's not like desktop OSes, which had been amd64 by default for a really long time.

Also, given lightningcss already supports 32-bit arm, I don't see a reason to don't support it *completely* instead of *partially*. In my opinion, either:

- You deprecate 32-bit arm completely if you can't give support to all the platform variants (including musl in this case).
- Or completely support the platform, giving support to all the platform variants.
