### ISSUE TITLE
Failed 500 Internal Server Error in the Deno

### ISSUE THREAD

**Issue by fwqaaq** [parcel-bundler/lightningcss#565]
Hey, bro, I got the following Error When I used the [examples](https://lightningcss.dev/docs.html) on your website.

It seems that this is caused by a lack of resources in the server.

```txt
error: Import 'https://unpkg.com/napi-wasm@1.1.0/index.mjs?module' failed: 500 Internal Server Error
    at https://unpkg.com/lightningcss-wasm@1.21.5/index.mjs?module:1:35
```

**Comment by devongovett** [comment]
Maybe unpkg had an outage, but looks fine now.

**Comment by fwqaaq** [comment]
>Maybe unpkg had an outage, but looks fine now.

@devongovett That doesn't seem useful to me.  The following errors appeared when I opened the [unpkg link](https://unpkg.com/napi-wasm@1.1.0/index.mjs?module).

```txt
SyntaxError: unknown: Support for the experimental syntax 'classProperties' isn't currently enabled (32:10):

  30 | 
  31 | export class Environment {
> 32 |   scopes = [];
     |          ^
  33 |   referenceId = 1;
  34 |   references = new Map();
  35 |   deferred = [null];

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.

undefined
```

**Comment by Lunarequest** [comment]
this is still true, I'm not sure why this was closed with 0 checks

**Comment by fwqaaq** [comment]
> this is still true, I'm not sure why this was closed with 0 checks

Yeah, and it's still that the way now.
