### ISSUE TITLE
ignore specific css from minification

### ISSUE THREAD

**Issue by tasiotas** [parcel-bundler/lightningcss#588]
Hi,

Is there a way to mark certain css lines for not being minified?

I have few variables that I would like not to be converted to hex, because they will be read in JS and expected to be in hsl format.
Right now I have to cover both cases, for dev and prod.

```css
  --text: hsl(240, 3%, 6%);
```

thank you

**Comment by devongovett** [comment]
No there is not. But maybe you could do something like this to get around it?

```css
--text-components: 240, 3%, 6%;
--text: hsl(var(--text-components));
```

Because `hsl` contains a variable it won't be able to be minified.

**Comment by tasiotas** [comment]
thank you! thats very helpful
