### ISSUE TITLE
Include a portable binary in releases

### ISSUE THREAD

**Issue by pepicrft** [parcel-bundler/lightningcss#591]
I'm building an [Elixir package](https://github.com/glossia/lightning_css) to ease the integration of Lightning CSS into Elixir projects, and it'd be awesome if this project provided portable binaries that we could pull and run from Elixir. I thought about doing that as part of the package and including the binaries in the Elixir package releases, but I think it makes more sense for those binaries to be provided by this project. What do you think?

For context, another Elixir package does something similar but for [esbuild](https://github.com/phoenixframework/esbuild). If you think it makes, I'd be happy to make the contribution myself with some guidance from your end.

**Comment by devongovett** [comment]
Binaries are in separate packages per architecture in order to keep the package size reasonable. Can you load the necessary binary from the npm registry (e.g. `lightningcss-darwin-x64`)?

**Comment by pepicrft** [comment]
But those aren't executables, are they? I believe they are files to be linked from a Node runtime,

**Comment by devongovett** [comment]
You could try the CLI binaries?

**Comment by Oriblish** [comment]
Renee ***@***.***

Preferences are the best for the specified catalog view

**Comment by pepicrft** [comment]
> You could try the CLI binaries?

Where can I get them from? Is there a list of URLs to download the CLIs for each of the supported architectures?

**Comment by mischnic** [comment]
See https://lightningcss.dev/docs.html#from-the-cli
The individual arch-specific packages are listed here: https://www.npmjs.com/package/lightningcss-cli?activeTab=dependencies

**Comment by pepicrft** [comment]
> See https://lightningcss.dev/docs.html#from-the-cli The individual arch-specific packages are listed here: https://www.npmjs.com/package/lightningcss-cli?activeTab=dependencies

This is exactly what I was looking for. Thanks @mischnic
