### ISSUE TITLE
oklch values converted to lab for Firefox 113 and up

### ISSUE THREAD

**Issue by illarionvk** [parcel-bundler/lightningcss#593]
OKLCH color space is [fully supported since Chrome 111 and Firefox 113](https://caniuse.com/mdn-css_types_color_oklch), but Lightning CSS still converts oklch() syntax to lab() for Firefox targets.

[Chrome 111 playground output — oklch preserved](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A7274496%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20background%3A%20oklch(55%25%200.22%2022)%3B%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

<img width="1392" alt="Screenshot 2023-10-02 at 14 15 00" src="https://github.com/parcel-bundler/lightningcss/assets/5012724/d073e0d9-7749-4fdd-89b1-5fc81c3ad2cd">

[Firefox 113+ playground output — oklch converted to lab](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22firefox%22%3A7405568%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20background%3A%20oklch(55%25%200.22%2022)%3B%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

<img width="1392" alt="Screenshot 2023-10-02 at 14 15 50" src="https://github.com/parcel-bundler/lightningcss/assets/5012724/fcb81b3b-27c3-429c-b7f6-3ed9d35fec18">

**Comment by devongovett** [comment]
Probably just need to update the browser compat data from caniuse/mdn.
