### ISSUE TITLE
`IntoOwned` as a trait, and implement it for nodes when `R` implements `IntoOwned`

### ISSUE THREAD

**Issue by kdy1** [parcel-bundler/lightningcss#596]
@devongovett Will you accept a PR for this?
If so, which crate should have `IntoOwned`?

**Comment by devongovett** [comment]
I think I originally tried to implement it as a trait and couldn't get it to work but I can't remember why. But if you get it working that sounds good to me. We can put the trait in here https://github.com/parcel-bundler/lightningcss/blob/master/src/traits.rs
