### ISSUE TITLE
Incorrect types for Declaration.type = "position". Maps to Position value instead of PositionLayout

### ISSUE THREAD

**Issue by marklawlor** [parcel-bundler/lightningcss#606]
The value for `position` (https://developer.mozilla.org/en-US/docs/Web/CSS/position) incorrectly map to the Position value, as used by `background-position`/gradients/etc

https://github.com/parcel-bundler/lightningcss/blob/eb280df5c135e647b05a409017ecb3ce6e337494/node/ast.d.ts#L2392-L2395

https://github.com/parcel-bundler/lightningcss/blob/eb280df5c135e647b05a409017ecb3ce6e337494/node/ast.d.ts#L7347-L7360

**Comment by devongovett** [comment]
Fixed by https://github.com/parcel-bundler/lightningcss/commit/eacdc71d118cefbc32171f2df95d427fe3fd69af
