### ISSUE TITLE
Not working with TailwindCSS + Vite

### ISSUE THREAD

**Issue by IHIutch** [parcel-bundler/lightningcss#608]
Everything seems to be set up correctly, it works with just Vite and PostCSS.

When I drop
```
css: {
        transformer: 'lightningcss',
        lightningcss: {
          targets: browserslistToTargets(browserslist('>= 0.25%'))
        }
      },
      build: {
        cssMinify: 'lightningcss'
      }
```
into the config, none of my CSS gets compiled. Not sure where the issue is? LightningCSS? Vite? Storybook?
      
[Reproduction](https://codesandbox.io/p/sandbox/bold-mestorf-kjgtvy?file=%2Fpackage.json%3A11%2C16)

**Comment by IHIutch** [comment]
Updating this ticket to reflect that this appears to be an issue with Vite & Tailwind, nothing to do with Storybook. I took the Lightning/Vite example from Stackblitz and dropped in Tailwind, but nothing gets compiled. Maybe Vite/Tailwind needs PostCSS? I don't know how it works under the hood

[Reproduction](https://stackblitz.com/edit/vitejs-vite-scn9nb)

**Comment by IHIutch** [comment]
Okay, apologies for my noise. It looks like Tailwind is using LightningCSS under the hood already (I'm not sure what version this started), but after rewatching the Tailwind keynote it looks like having Tailwind as a [PostCSS plugin is still required](https://youtu.be/CLkxRnRQtDE?si=ENeIhzhBanHG__GS&t=3020), for now.

That said, I don't think LightningCSS plugin is needed when using Vite. From what I can tell, LightningCSS is already handling the Tailwind generation.

**Comment by oaoxd0314** [comment]
Thank you for solving my problem.
