### ISSUE TITLE
Segmentation Fault error on calc()/clamp() expression

### ISSUE THREAD

**Issue by illarionvk** [parcel-bundler/lightningcss#611]
The transform() compiler module crashes the Node process with a segfault on a calc()/clamp() expression:

```css
.item {
  width: calc(100% - clamp(1.125rem, 1.25vw, 1.2375rem) - clamp(1.125rem, 1.25vw, 1.2375rem));
}
```

[The playground also shows `index out of bounds` error](https://lightningcss.dev/playground#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.item%20%7B%5Cn%20%20width%3A%20calc(100%25%20-%20clamp(1.125rem%2C%201.25vw%2C%201.2375rem)%20-%20clamp(1.125rem%2C%201.25vw%2C%201.2375rem))%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D) and stops responding to code changes.

If I use the css declaration directly in a browser, the element calculates the width correctly.

Tested on lightningcss version 1.22.0, Node versions 18.18.0 and 16.19.0, amd64 Linux

<img width="2032" alt="Screenshot 2023-10-23 at 12 39 20" src="https://github.com/parcel-bundler/lightningcss/assets/5012724/2f54d17d-7d16-4e4d-9345-336bb329683f">

Related issue from last year:
https://github.com/parcel-bundler/lightningcss/issues/166

**Comment by illarionvk** [comment]
I tried excluding the `ClampFunction` feature, but it still crashes.

**Comment by yisibl** [comment]
Please raise the priority of this error.
