### ISSUE TITLE
Wrong minify result of `min-height: -webkit-fill-available;`

### ISSUE THREAD

**Issue by magic-akari** [parcel-bundler/lightningcss#630]
## Description

> Firefox does not support the height/min-height/max-height properties, only width. See [test case](https://codepen.io/shshaw/pen/Kiwaz), [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=567039).

-- From caniuse

## Version
1.22.1

## Keyword

- minify
- firefox
- unsupported properties

## Code

```CSS
html {
    min-height: 100vh;
    min-height: -webkit-fill-available;
}
```

[Playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22firefox%22%3A7798784%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22html%20%7B%5Cn%20%20%20%20min-height%3A%20100vh%3B%5Cn%20%20%20%20min-height%3A%20-webkit-fill-available%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%221.22.1%22%7D)

## Expacted result

`min-height: 100vh;` should be preserved

## Actual result

`min-height: 100vh;` is removed

**Comment by magic-akari** [comment]
Investigation:
It's introduced by e25521014691ebc13ee889a4ebf5b78f14ea1b6a

**Comment by yisibl** [comment]
This can cause properties to be lost, please raise the priority of this error.
