### ISSUE TITLE
display: -webkit-flex output different according to the code order

### ISSUE THREAD

**Issue by enjoyma** [parcel-bundler/lightningcss#637]
Why the output is different? Expect the output is same.

[playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20%20display%3A%20-webkit-flex%3B%5Cn%20%20%20display%3A%20flex%3B%5Cn%7D%5Cn%5Cn.bar%20%7B%5Cn%20%20%20display%3A%20flex%3B%5Cn%20%20%20display%3A%20-webkit-flex%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

![image](https://github.com/parcel-bundler/lightningcss/assets/9302905/b18ae748-e2c8-498b-883c-404cf9b648a3)

**Comment by devongovett** [comment]
This is equivalent. in both rules, the same property is repeated, so the last value wins.
