### ISSUE TITLE
`:after .header` causes `Unexpected token Delim('.')`

### ISSUE THREAD

**Issue by DreierF** [parcel-bundler/lightningcss#648]
I was trying out lightningcss as css minifier for our codbase and ran into a parser error with the message `Unexpected token Delim('.')`.

Minimum reproduction:
```css
div:after .header {
  color: #FFFFFF;
}
```
[Playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22div%3Aafter%20.header%20%7B%5Cn%20%20color%3A%20%23FFFFFF%3B%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

The selector originates from [this line](https://github.com/Semantic-Org/Semantic-UI-LESS/blob/master/definitions/modules/popup.less#L230) in a third-party dependency.

**Comment by devongovett** [comment]
This is correct. Pseudo elements cannot contain other elements so this selector is invalid.

**Comment by devongovett** [comment]
You can work around the issue in the third party dependency by enabling the errorRecovery option, which will just ignore that rule entirely. https://lightningcss.dev/docs.html#error-recovery

**Comment by DreierF** [comment]
Ok, thanks for swift response!
I did run the code through https://jigsaw.w3.org/css-validator/ before submitting the issue and it said it would be valid, even though I also was not sure how you could have ended up with an element within `:after`.

Unfortunately, setting `css.lightningcss.errorRecovery` does not seem to be picked up when using `lightningcss` only as a minifier in Vite, but that's a Vite issue then.
