### ISSUE TITLE
lightningcss - modification preserving colour value (non shorthand).

### ISSUE THREAD

**Issue by nileshprajapati** [parcel-bundler/lightningcss#677]
Hi
​
Is there a way to preserve the author's colour values when lightningcss minifies the CSS?
​
I'm currently migrating from postcss using Vite.
​
Reading through the documentation, I understand that the colour values and calc function are shorthand with lightningcss for optimisation. 
​
Thanks,
Nilesh

**Comment by devongovett** [comment]
No. Why do you need this?

**Comment by nileshprajapati** [comment]
I oversee multiple projects that undergo routine design audits to uphold consistency and adhere to best practices.

To meet the criteria of each design audit, every project follows a set brand guideline and design system. We strictly use recommended color formats to maintain consistency.

**Comment by devongovett** [comment]
Ok but that would be in your source code not your compiled code right?

**Comment by nileshprajapati** [comment]
Our design audits occur post compilation of code.

**Comment by devongovett** [comment]
I don't think that's a good idea. The point of using a minifier is to reduce the size of the code as much as possible. Converting `rgb(...)` to `#abc` is a lossless transform that reduces the file size. Thus disabling it would be counterproductive. I suggest doing lints/audits on source code not compiled code.
