### ISSUE TITLE
generated classes beginning with a numeral can break JS strict mode

### ISSUE THREAD

**Issue by vpanta** [parcel-bundler/lightningcss#704]
It seems like when `lightningcss` generates a classname that begins with a numeral, it does the correct thing and [escapes the character](https://www.w3.org/TR/css-syntax-3/#escaping). However, this can create an Octal Escape Sequence, which then fails when processed in JS's `strict` mode.

We ran into this when using `lightningcss` alongside `jest-environment-jsdom`, where `nwsapi` (used via `jsdom`) generates some strict-mode functions which then choke on these escape sequences.

An example of it creating this kind of sequence can be seen in https://github.com/vpanta/lightningcss-octal-escape and by running `node index.js`.

I'm not certain the best route here, but think it could be as simple as `lightningcss` prepending an alphabetic character when the classname would otherwise begin with a numeral.

**Comment by devongovett** [comment]
Maybe I'm missing something, but why would CSS be parsed by JS?

**Comment by vpanta** [comment]
As noted, this is coming [from `nwsapi`](https://www.npmjs.com/package/nwsapi), included in our build [via `jsdom`](https://www.npmjs.com/package/jsdom). And it's getting triggered via `jsdom`'s `getComputedStyle` functionality. I figured I'd raise it here because class-names generally shouldn't start with a numeral anyways, but I could see a reason to say it's a bug over there (`nwsapi`) instead though.

**Comment by mischnic** [comment]
There are some existing issues on nwsapi already: https://github.com/dperini/nwsapi/issues/105 or https://github.com/dperini/nwsapi/issues/92

**Comment by vpanta** [comment]
Welp, shows what I know, I was digging in the wrong place. I'll close this, thanks for the assist!
