### ISSUE TITLE
Usage with Vite performance question

### ISSUE THREAD

**Issue by Neevalt** [parcel-bundler/lightningcss#706]
Hello, 

I wanted to give a try to lightningcss on my Vue project using vite. However, using Vite's debug tools, I see that the CSS part of my components is taking actually longer with lightningcss vs postcss with the vite:plugin-transform.

You can see it in action here : https://stackblitz.com/edit/vitejs-vite-veyt6b?file=vite.config.js&terminal=dev

Just change the `vite.config.js` file's `css.transformer` from `lightningcss` to `postcss`, then run `DEBUG="vite:plugin-transform" npm run dev`.

However both are quite "slow" on stackblitz, the difference is quite drastic once the project is cloned on my own machine (as in, vite:css takes ~0.1ms with postcss, and around ~30ms with lightnincss).

Any idea why that difference is and if it can be adressed ?

Thank you in advance 😃

**Comment by devongovett** [comment]
I don't really have time to investigate this for you but let me know if you figure it out.
