### ISSUE TITLE
Unable to obtain Px in LengthUnit 

### ISSUE THREAD

**Issue by CWH0908** [parcel-bundler/lightningcss#717]
When my style unit is Px, I see that the type returned by LengthUnit is px. How can I distinguish the unit types of Px?
It is supported by default in postcss

**Comment by CWH0908** [comment]
> I don't follow what you mean here. Are you talking about the upper case to lower case conversion? If so, that shouldn't matter - css is case insensitive.

Postcss defaults to not converting Px and PX, and outputs the original Px and PX,

But this does not work in lightningcss, as both Px and PX in the style are converted as px to rem,

I don't seem to have found the configuration in the document. How can I not convert PX and Px to px,

The display in LengthUnit shows that Px and PX have been converted to px

**Comment by devongovett** [comment]
I still don't understand. CSS is case insensitive, so Px, pX, PX, and px are all equivalent. Why does the case matter for your application?

**Comment by CWH0908** [comment]
> I still don't understand. CSS is case insensitive, so Px, pX, PX, and px are all equivalent. Why does the case matter for your application?

The root node size in our project is written as Px. For example, if I set the font size of HTML to 60Px, I would like it to retain Px output like in Postcss, instead of converting to Rem
However, in lightningcss, this Px was converted to rem, resulting in the root node size of the HTML not matching the original postcss scheme
I tried not to convert Px type in obtaining unit type, but LengthUnit will convert Px to lowercase px, which makes it difficult for me to determine whether the original unit is Px or px
So, does lightningcss support determining if the unit type is Px, so that I can handle it without converting to rem?

**Comment by mischnic** [comment]
So in your project, you have the *convention* that `Px` and `px` are different. And you're asking if Lightning CSS could preserve that difference.

I think the answer is no. And this this is unlikely to change as it's indeed equivalent according to the CSS spec.

What you really want are custom units: https://github.com/parcel-bundler/lightningcss/issues/221, which appear to be supported with a transformer.

**Comment by CWH0908** [comment]
> So in your project, you have the **convention** that `Px` and `px` are different. And you're asking if Lightning CSS could preserve that difference.
> 
> I think the answer is no. And this this is unlikely to change as it's indeed equivalent according to the CSS spec.
> 
> What you really want are custom units: #221, which appear to be supported with a transformer.

Does that mean I can customize Px types?

**Comment by mischnic** [comment]
There's an example in https://github.com/parcel-bundler/lightningcss/issues/221#issuecomment-1371229900 for how to use a custom unit.

You can't use `Px` specifically, but literally anything else that doesn't conflict with normal CSS: [example](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%20%20%20%20%20%20%20.foo%20%7B%20%5Cn%20%20%20%20%20%20%20%20%20width%3A%204foo%3B%5Cn%20%20%20%20%20%20%20%20%20height%3A%204--bar%3B%5Cn%20%20%20%20%20%20%20%20%20font-size%3A%203px%3B%20%5Cn%20%20%20%20%20%20%20%7D%20%22%2C%22visitorEnabled%22%3Atrue%2C%22visitor%22%3A%22%7B%5Cn%20%20Token%3A%20%7B%5Cn%20%20%20%20dimension(token)%20%7B%5Cn%20%20%20%20%20%20console.log(token)%3B%5Cn%20%20%20%20%20%20if%20(token.unit%20%3D%3D%20%5C%22foo%5C%22)%20%7B%5Cn%20%20%20%20%20%20%20%20return%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20type%3A%20%5C%22length%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%20%20value%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20unit%3A%20%5C%22px%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20value%3A%20token.value%20*%2010%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%7D%3B%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20if%20(token.unit%20%3D%3D%20%5C%22--bar%5C%22)%20%7B%5Cn%20%20%20%20%20%20%20%20return%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20type%3A%20%5C%22length%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%20%20value%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20unit%3A%20%5C%22em%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20value%3A%20token.value%20*%2010%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%7D%3B%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%2C%5Cn%20%20%7D%2C%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

**Comment by ckken** [comment]
postcss use PX when px to rem,the PX is not transform

**Comment by ckken** [comment]
https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.cssModule%20%7B%5Cn%20%20background%3A%20%23f7f7f7%3B%5Cn%20%20padding%3A%2020px%3B%5Cn%20%20margin-top%3A%2020px%3B%5Cn%7D%5Cn%5Cn.f%20%7B%5Cn%20%20color%3A%20blue%3B%5Cn%7D%5Cn%5Cn.pxIgnore%20%7B%5Cn%20%20font-size%3A%20120-px%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Atrue%2C%22visitor%22%3A%22%7B%5Cn%20%20Token%3A%20%7B%5Cn%20%20%20%20%20dimension(token)%20%7B%5Cn%20%20%20%20%20%20%20if(token.unit%3D%3D%3D'-px')%7B%5Cn%20%20%20%20%20%20%20%20return%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20type%3A%20%5C%22length%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%20%20value%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20unit%3A%20%5C%22px%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20value%3A%20token.value%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%7D%3B%5Cn%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20Length(length)%20%7B%5Cn%20%20%20%20%20%20console.log('length'%2C%20length)%5Cn%20%20%20%20%20%20if%20(length.unit%20%3D%3D%3D%20'px')%20%7B%5Cn%20%20%20%20%20%20%20%20if%20(length.value%20%3E%201)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20return%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20unit%3A%20'rem'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20value%3A%20length.value%20%2F%2016%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%2C%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D

**Comment by ckken** [comment]
what about https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.cssModule%20%7B%5Cn%20%20background%3A%20%23f7f7f7%3B%5Cn%20%20padding%3A%2020px%3B%5Cn%20%20margin-top%3A%2020px%3B%5Cn%7D%5Cn%5Cn.f%20%7B%5Cn%20%20color%3A%20blue%3B%5Cn%7D%5Cn%5Cn.pxIgnore%20%7B%5Cn%20%20font-size%3A%20120-px%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Atrue%2C%22visitor%22%3A%22%7B%5Cn%20%20Token%3A%20%7B%5Cn%20%20%20%20%20dimension(token)%20%7B%5Cn%20%20%20%20%20%20%20if(token.unit%3D%3D%3D'-px')%7B%5Cn%20%20%20%20%20%20%20%20return%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20type%3A%20%5C%22length%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%20%20value%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20unit%3A%20%5C%22px%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20value%3A%20token.value%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20ignore%3Atrue%2F%2F%20can%20we%20add%20ignore%20to%20length%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%7D%3B%5Cn%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20Length(length)%20%7B%5Cn%20%20%20%20%20%20console.log('length'%2C%20length)%5Cn%20%20%20%20%20%20if%20(length.unit%20%3D%3D%3D%20'px')%20%7B%5Cn%20%20%20%20%20%20%20%20if%20(length.value%20%3E%201)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20return%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20unit%3A%20'rem'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20value%3A%20length.value%20%2F%2016%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%2C%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D
