### ISSUE TITLE
LightningCSS doesn't recognize currentcolor as valid value

### ISSUE THREAD

**Issue by ghost** [parcel-bundler/lightningcss#721]
Hello.

When I write the following:

```
box-shadow:
  oklch(100% 0 0deg / 50%) 0 0.63rem 0.94rem -0.19rem,
  currentColor 0 0.44rem 0.8rem -0.58rem;
```

or

```
box-shadow:
  oklch(100% 0 0deg / 50%) 0 0.63rem 0.94rem -0.19rem,
  0 0.44rem 0.8rem -0.58rem;
```

Then, when I run the build process of Vite, it happens this error:
```
thread '<unnamed>' panicked at src/properties/box_shadow.rs:211:44:
called `Result::unwrap()` on an `Err` value: ()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

The error is gone when I write:

```
box-shadow:
  oklch(100% 0 0deg / 50%) 0 0.63rem 0.94rem -0.19rem,
  gray 0 0.44rem 0.8rem -0.58rem;
```

There is no equivalent for currentColor/currentcolor. This is a valid syntax. Please support it in Lightning CSS.

https://stackblitz.com/edit/vitest-dev-vitest-flshbv?file=package.json

Reference: https://github.com/vitejs/vite/issues/16461

**Comment by mischnic** [comment]
It's apparently that combination of oklch and currentColor that is broken:

[oklch and currentColor panics](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22body%7B%5Cn%20%20box-shadow%3A%5Cn%20%20oklch(100%25%200%200deg%20%2F%2050%25)%200%200.63rem%200.94rem%20-0.19rem%2C%5Cn%20%20currentColor%200%200.44rem%200.8rem%20-0.58rem%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

[oklch and simple color is fine](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22body%7B%5Cn%20%20box-shadow%3A%5Cn%20%20oklch(100%25%200%200deg%20%2F%2050%25)%200%200.63rem%200.94rem%20-0.19rem%2C%5Cn%20%20grey%200%200.44rem%200.8rem%20-0.58rem%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

[simple color and currentColor is fine](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22body%7B%5Cn%20%20box-shadow%3A%5Cn%20%20grey%200%200.63rem%200.94rem%20-0.19rem%2C%5Cn%20%20currentColor%200%200.44rem%200.8rem%20-0.58rem%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)
