### ISSUE TITLE
Minifier Breaks Black Translucent Colors

### ISSUE THREAD

**Issue by dev-nicolaos** [parcel-bundler/lightningcss#727]
## Environment

Operating Systems Tested On: Windows 10 Enterprise 22H2, Fedora Linux 40

Node Version: 20.10.0

LightningCSS Version: 1.24.1

## Steps to Reproduce

- Clone the [reproduction repo](https://github.com/dev-nicolaos/lightningcss-black-transparency-bug)
- Run `npm ci` to install lightningcss
- Run `npm run bundle-css`

## Expected Outcome

All the custom properties in _bundled.css_ will have valid color values as specified in _main.css_

## Actual Outcome

Only the white transparency and red color are output correctly. All the black transparencies have the `0 0 0` before the `/` in the `color` function removed (e.g. `--Black-60:color(display-p3/.6);`) in _bundled.css_ making them impossible for the browser to render.

## Notes

I feel confident the issue is with the minifiying step. If you set `minify` to `false` in the call to `bundle` in _bundle.js_, the output values are valid.

**Comment by mischnic** [comment]
[Playground reproduction](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%3Aroot%20%7B%5Cn%20%20%20%20--Black-60%3A%20color(display-p3%200%200%200%20%2F%200.6)%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)
