### ISSUE TITLE
Using Lightning as a code generator

### ISSUE THREAD

**Issue by devinhalladay** [parcel-bundler/lightningcss#728]
Hello! First off, thanks for this library, it's really cool and has made its way into many of my side projects lately.

I'm currently building a Figma Codegen plugin to turn Figma's auto-generated CSS into usable code for our internal styling framework called RCSS. RCSS is a Typescript styling utility similar to Tailwind, where styles are applied via Emotion using a clean syntax like `rcss.p(8)` for padding on all sides, `rcss.px(8)` for padding on left/right, `rcss.backgroundColor(tokens.backgroundRoot)` for backgrounds, etc. RCSS code is typically an array of these function calls.

I'm wondering if Lightning could be used basically to transform raw CSS into this custom syntax. Maybe via [custom transforms](https://lightningcss.dev/transforms.html)?

**Comment by devongovett** [comment]
It's not really designed for that. I'd recommend using postcss or another tool

**Comment by TheUltDev** [comment]
@devinhalladay it's possible, here's a reference:
