### ISSUE TITLE
Allow use of "resolver" when using through vite

### ISSUE THREAD

**Issue by olivierbossel** [parcel-bundler/lightningcss#735]
Hi guys,

Hope you are doing all well!
First, thanks for your awesome job, really appreciate it!

My "issue" is more a feature request.
Is that possible to add support for the custom "resolver" when using lightningcss through vite?

I would like to add support for globs in my `@import` but when I specify a custom resolver in the config using vite, it seems that the resolver is not taken in consideration:

```js
// vite.config.ts
import { browserslistToTargets } from "lightningcss";
import fs from 'fs';
import path from 'path';

export default {
  css: {
    transformer: "lightningcss",
    lightningcss: {
      resolver: {
        read(filePath) {
          console.log(filePath);
          return fs.readFileSync(filePath, "utf8");
        },
        resolve(specifier, from) {
          return path.resolve(path.dirname(from), specifier);
        },
      },
      targets: browserslistToTargets(browserslist(">= 0.25%")),
    },
  },
  build: {
    cssMinify: "lightningcss",
  },
};
```

I will be happy to help if needed!
See you!

**Comment by devongovett** [comment]
I think you'd need to open this issue on the Vite repo. They may not be passing through all of the options to Lightning CSS.
