### ISSUE TITLE
Minification strips required whitespace between consecutive `var(...)` calls

### ISSUE THREAD

**Issue by adamwathan** [parcel-bundler/lightningcss#736]
Given some input like this:

```css
.foo {
  background: var(--one) var(--two);
}
```

Lightning minifies it to this:

```css
.foo{background:var(--one)var(--two)}
```

Here's a quick reproduction in the playground:

[Lightning CSS Playground reproduction](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20background%3A%20var(--one)%20var(--two)%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

Safari and Chrome seem to handle this okay but Firefox doesn't, and the space between the two `var(…)` calls is necessary for Firefox to compute the correct value.

Take a look at the computed value of `translate` on the right in the two screenshots below:

**Without a space:**

![image](https://github.com/parcel-bundler/lightningcss/assets/4323180/e61a5152-732d-40b9-a4f8-5bec9076256f)

**With the space:**

![image](https://github.com/parcel-bundler/lightningcss/assets/4323180/aa9a6124-476c-4863-94ae-d7a94fdcace6)

We noticed this bug because our [Switch demo](https://headlessui.com/react/switch) in the new Headless UI docs doesn't work right now (make sure to use Firefox Nightly where `@property` is supported or you'll see all sorts of other issues).

**Comment by devongovett** [comment]
hmm, this seems to work for me: https://codepen.io/devongovett/pen/zYQOXKG Is it specific to @property?

Seems like this might be a Firefox bug? The spec is pretty clear that whitespace shouldn't matter here.

**Comment by thecrypticace** [comment]
@devongovett looks like a Firefox bug with an `@property` with the `<length-percentage>` syntax: https://codepen.io/thecrypticace/pen/dyEbBdo

If you change the syntax to `<length>` it starts working again.

**Comment by adamwathan** [comment]
Yeah seems like this is a Firefox Nightly bug that triggers under very odd and specific circumstances, so ignore this one I suppose. Super strange!
