### ISSUE TITLE
Color value format

### ISSUE THREAD

**Issue by CWH0908** [parcel-bundler/lightningcss#737]
The color values in the style have been converted

For example: background color: rgba ($color: # ae2e6b, $alpha: 0.3); It will be converted to background color: rgba (174,46107,. 3):

How to maintain the original color value format?

**Comment by devongovett** [comment]
It should produce an equivalent color that's also smaller. What problem is this causing for you?

**Comment by CWH0908** [comment]
> It should produce an equivalent color that's also smaller. What problem is this causing for you?

But I cannot directly search for the color values displayed by the page checker in the code,
If I can configure the original format output, then I can easily search for the corresponding style in the code for easy modification

**Comment by devongovett** [comment]
Lightning CSS output is not meant for human readability. It is meant to produce the smallest and most compatible output for browsers to consume. If you're looking for a formatter or something like that I'd suggest using a different tool.

**Comment by romainmenke** [comment]
@CWH0908 you might like https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-minify#readme

It minifies your CSS without actually changing it ;)
