### ISSUE TITLE
/* ERROR: Unexpected token Semicolon */ (IE hacks 5-7)

### ISSUE THREAD

**Issue by PanSom** [parcel-bundler/lightningcss#765]
A bug on hacks from the time of the dinosaurs.
Yes I realise all this myself, but I had to work with creepy legacy and what's creepy is that I used to write it myself. But that's not the point.

The point is that lightningcss reports errors in css lines like this.

```
p {
  border:1px solid green; /* works in all */
  *border:1px solid red; /* targets IE6 and 7 */
  _border:1px solid blue; /* targets IE6 */
}
```

Again, I get it. It's no longer about supporting such ancient browsers. But if such an ancient css lib comes across, I wouldn't want it to crash on such lines.

**Comment by devongovett** [comment]
Please see the docs for the error recovery option. https://lightningcss.dev/docs.html#error-recovery

**Comment by PanSom** [comment]
Thanks, I wasn't paying attention.
