### ISSUE TITLE
light-dark() is always being replaced

### ISSUE THREAD

**Issue by jcayzac** [parcel-bundler/lightningcss#773]
The `--lightningcss-light/--lightningcss-dark` polyfill always gets generated on 1.25.1, even if I pass:

```js
{
  targets: { chrome: 126 },
  include: 0,
  exclude: 0xffffffff,
}
```

How can I disable that? `light-dark()` is supported by all major browsers, and for chrome specifically since 123.

I also didn't expect any transpilation if I disabled all the features. Just minification.

**Comment by jcayzac** [comment]
Shouldn't this behavior be governed by `Features.ColorFunction` ?

**Comment by jcayzac** [comment]
Hmm even if I enforce the latest versions of `caniuse-lite` and `@mdn/browser-compat-data`, it still injects it…

**Comment by jcayzac** [comment]
With `targets: {}` it works.

**Comment by sven-meyer-wetter-com** [comment]
I've the same problem....

**Comment by devongovett** [comment]
See the docs for how to configure targets: https://lightningcss.dev/transpilation.html#browser-targets

you need `chrome: 126 << 16`
