### ISSUE TITLE
How to recover substituted variables?

### ISSUE THREAD

**Issue by AlbertMarashi** [parcel-bundler/lightningcss#776]
I'd like a way to recover substituted variables. I'm building a CMS where I want to retain references to the original variables. I'm using lightning CSS to serialize the CSS string into an AST and then back into a CSS string.

How do I go about this?

Shouldn't there be some kind of way to have like:

```css
background: var(--background);
```
Converting into an AST of the `Property::Background` such that the `color` field exists as:

```rs
Background {
    color: Variable(...),
    ...
}
```

I'm happy passing in a hashmap of variables such that they can be used in the parsing to know what the variable actually is for the system to parse

Such that when it is converted back `to_css_string()` it turns into
```css
background: var(--background)
```
?

**Comment by devongovett** [comment]
There is a `substitute_variables` method on `UnparsedProperty` under a feature flag: https://docs.rs/lightningcss/latest/lightningcss/properties/custom/struct.UnparsedProperty.html#method.substitute_variables

**Comment by AlbertMarashi** [comment]
I want to do the opposite of that, but anyhow I ended up writing my own CSS parser for my usecase. I think it would be too difficult to implement here
