### ISSUE TITLE
Support for anchor positioning

### ISSUE THREAD

**Issue by tounsoo** [parcel-bundler/lightningcss#779]
CSS has the new anchor positioning API and I'm super excited for this. Although it's available in latest Chrome, I was wondering if lightningCSS could have make something to support Safari and past few Chrome versions. 

Thank you! 
(Also want to mention that lightningCSS has been a life saver for me and I love you guys!)

https://developer.chrome.com/blog/anchor-positioning-api

**Comment by devongovett** [comment]
I don't think it's possible to polyfill this in only CSS, you'd need a lot of JS for that. I'd take a look at something like [floating-ui](https://floating-ui.com).
