### ISSUE TITLE
Using both backdrop-filter and -webkit-backdrop-filter removes backdrop-filter

### ISSUE THREAD

**Issue by tsevasa** [parcel-bundler/lightningcss#785]
In a nutshell, Chrome and Firefox need `backdrop-filter`, while Safari needs `-webkit-backdrop-filter`. So I am using both of these properties in my CSS for development. However, when building with Lightning CSS, `backdrop-filter` gets removed, but _only in the presence of_ `-webkit-backdrop-filter`, which is very weird.

Comparison: [Playground link 1](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A7929856%2C%22firefox%22%3A1310720%2C%22safari%22%3A262144%2C%22opera%22%3A262144%2C%22edge%22%3A7929856%2C%22ie%22%3A262144%2C%22ios_saf%22%3A1114112%2C%22android%22%3A131072%2C%22samsung%22%3A196608%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20backdrop-filter%3A%20blur(10px)%3B%5Cn%20%20-webkit-backdrop-filter%3A%20blur(10px)%3B%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D), [Playground link 2](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A7929856%2C%22edge%22%3A7929856%2C%22ios_saf%22%3A1114112%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20backdrop-filter%3A%20blur(10px)%3B%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D).

**Comment by devongovett** [comment]
The webkit prefix must be before the unprefixed version

**Comment by tsevasa** [comment]
Thanks!
