### ISSUE TITLE
[bug]lighting css will shuffle css properties order

### ISSUE THREAD

**Issue by sbyps** [parcel-bundler/lightningcss#805]
![img_v3_02e8_5f9d4970-3d6e-4ccf-8b7f-f25f0f7f5b0g](https://github.com/user-attachments/assets/2d35a1e7-7da0-4a7b-9196-7b652f191428)
![img_v3_02e8_44f16586-43a8-4f71-8975-a1dc5f0c19bg](https://github.com/user-attachments/assets/89c3a419-3ad9-4794-b74f-0d4ba56cfadf)

**Comment by matthiask** [comment]
The same thing happened to us as well. `height:auto` was ordered after `height:calc(...)` after minimization instead of before. (`height:auto` shouldn't have been there in the first place, but the change was definitely unexpected.)

**Comment by matthiask** [comment]
Here's a minimal example showing the breakage:

```javascript
import fs from "node:fs";
import { transform } from 'lightningcss';

let style = `
.navigation {
    height: auto;
    height: calc(100vh - var(--header-height, 0rem));
}
`

let { code, map } = transform({
  filename: 'style.css',
  code: Buffer.from(style),
  minify: true,
  sourceMap: true
});

fs.writeFileSync(1, code);
console.log()
```

See:

```shell
$ node minify.mjs 
.navigation{height:calc(100vh - var(--header-height,0rem));height:auto}
$
```

The `height:auto` now overrides the `calc()` value instead of being overridden by it.
