### ISSUE TITLE
Minifier does not preserve values of CSS custom property

### ISSUE THREAD

**Issue by carbotaniuman** [parcel-bundler/lightningcss#807]
I use CSS custom properties to store some tags to be later read by JavaScript. LightningCSS does not seem to adhere to the CSS spec and messes with the custom property values.

Given:
```
.t {
  --tag: 8e64;
}
```

Output
```
.t{--tag:3.40282e38}
```

Expected
```
.t{--tag:8e64}
```

**Comment by devongovett** [comment]
CSS numbers are represented as 32-bit floating point in Lightning CSS and most browsers, and you are hitting the maximum value. This is done during parsing by Firefox's parser which we reuse in Lightning CSS: https://github.com/servo/rust-cssparser/blob/b75ce6a8df2dbd712fac9d49ba38ee09b96d0d52/src/tokenizer.rs#L73 The spec leaves the precision of supported values as [implementation defined](https://drafts.csswg.org/css-values-4/#numeric-types), but according to [this thread](https://github.com/w3c/csswg-drafts/issues/4551) most implementations use single precision floating point. Therefore I don't believe we are violating any spec here and I don't think this would be very easy to change.

**Comment by carbotaniuman** [comment]
I'm not sure this is correct - this is about CSS custom properties here, which I believe have different results. For example, given this CSS

```
#a {
--foo: 8e64
}

#b {
--foo: 8e64-1234
}
```
Running this in Chrome (with some appropriate dummy elements), the following output is given:

```
document.getElementById("a").style.getPropertyValue("foo")
'8e64'
```
and
```
document.getElementById("b").style.getPropertyValue("foo")
'8e64-1234'
```
