### ISSUE TITLE
Don't add animation-timeline to animation shorthand 

### ISSUE THREAD

**Issue by dkirchhof** [parcel-bundler/lightningcss#815]
Hey,

the animation-timeline value will be added to the animation shorthand, which is - according to https://developer.chrome.com/docs/css-ui/scroll-driven-animations - invalid.

> Note: The animation-timeline longhand property is not part of the animation shorthand and must be declared separately. Furthermore, animation-timeline must be declared after the animation shorthand as the shorthand will reset non-included longhands to their initial value.

---

example (using v1.27.0):

input:
```css
animation: header linear forwards;
animation-timeline: scroll();
```

output:
```css
animation: linear forwards header scroll();
```

browser output:
![image](https://github.com/user-attachments/assets/b76e00bd-2884-4a74-97b8-5a71c548f92b)

**Comment by devongovett** [comment]
It is according to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/animation) and the [Spec](https://drafts.csswg.org/css-animations-2/#animation-shorthand).

This may not be supported by all browsers yet, so Lightning CSS will only combine it into the shorthand when it is supported. [Example](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6553600%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20animation%3A%20header%20linear%20forwards%3B%5Cn%20%20animation-timeline%3A%20scroll()%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D) If it's being combined unexpectedly, make sure you set your browser targets appropriately.

**Comment by dkirchhof** [comment]
Oh got it. Thanks for clarification.
