### ISSUE TITLE
[@media] Incorrect logical operator transformation

### ISSUE THREAD

**Issue by beefchimi** [parcel-bundler/lightningcss#817]
### Problem

`@media` logical operators get transformed incorrectly.

### Context

- If I write `@media (width < 100) {}`, that means I want styles to apply when the `window` is between _(and including)_ `0-99` pixels in `width`.
- Similarly, if I write `@media (width > 100) {}`, I want styles to apply when the `window` is between _(and including)_ `101-infinity` pixels in `width`.
- If I wanted my logical operation to be inclusive, then I would use an inclusive operator such as `@media (width >= 100) {}`.

The `lightningcss` transformation applied to these logical operators appears not to take this into consideration. Here is a screenshot [from the playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%40media%20(width%20%3E%201024px)%20%7B%5Cn%20%20.a%20%7B%5Cn%20%20%20%20color%3A%20green%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%40media%20(width%20%3C%201024px)%20%7B%5Cn%20%20.a%20%7B%5Cn%20%20%20%20color%3A%20red%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D):

![screen](https://github.com/user-attachments/assets/a4b94861-529b-43df-8e32-2c0405a13175)

### Solution

If a logical `<` or `>` is used, we need to either `subtract` or `add` a single pixel. If I am not mistaken, `@media` queries only work against `px` units, so there _shouldn't be_ concern about handling other units, such as `em` or `rem`.

**Comment by pepelsbey** [comment]
This a bug that can hide content at certain resolutions. For example, if you’re using one version of navigation menu on mobile (and hiding in on desktop) and other version on desktop (and hiding it on mobile). I’d say it’s high-priority.

**Comment by pepelsbey** [comment]
Yes, it’s definitely a duplicate of https://github.com/parcel-bundler/lightningcss/issues/228#issuecomment-2454669869: try using a viewport width of 1000px or less, and it will work just fine. I’d recommend closing this issue and focusing on https://github.com/parcel-bundler/lightningcss/issues/228.

**Comment by beefchimi** [comment]
Closed as duplicate.
