### ISSUE TITLE
"@property" is not supported

### ISSUE THREAD

**Issue by z4o4z** [parcel-bundler/lightningcss#820]
Looks like [typed CSS properties](https://developer.mozilla.org/en-US/docs/Web/CSS/@property) are not supported, getting `ERROR: Invalid @ rule body`:

```css
@property --typed-name {
  syntax: "<number>";
  inherits: false;
}
```

Playground: https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%40property%20--typed-name%20%7B%5Cn%20%20syntax%3A%20%5C%22%3Cnumber%3E%5C%22%3B%5Cn%20%20inherits%3A%20false%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D

**Comment by devongovett** [comment]
initial-value is required.

**Comment by z4o4z** [comment]
> initial-value is required. Error message could be better but it is indeed invalid.

MDN says it's not required, and it works without initial value in chrome...

**Comment by devongovett** [comment]
Browsers will skip over the rule if it is invalid so that's what you're seeing in chrome. And yes, initial-value is not required when using * as the syntax.
