### ISSUE TITLE
license comment `/*! ... */` will be removed when minify.

### ISSUE THREAD

**Issue by r-plus** [parcel-bundler/lightningcss#830]
I expected all of the license comment (start with `/*!`) will not removed when minify.
But lightningcss v1.27.0 is only keep the first license comment.
Is this expected behavior?

[Playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6553600%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%2F*!%20foo%20*%2F%5Cnp%20%7B%5Cn%20%20font-size%3A%201em%3B%5Cn%7D%5Cn%2F*!%20bar%20*%2F%5Cn%2F*!%5Cn%20*%20jQuery%20UI%20CSS%20Framework%201.13.0%5Cn%20*%20http%3A%2F%2Fjqueryui.com%5Cn%20*%5Cn%20*%20Copyright%20jQuery%20Foundation%20and%20other%20contributors%5Cn%20*%20Released%20under%20the%20MIT%20license.%5Cn%20*%20http%3A%2F%2Fjquery.org%2Flicense%5Cn%20*%5Cn%20*%20http%3A%2F%2Fapi.jqueryui.com%2Fcategory%2Ftheming%2F%5Cn%20*%5Cn%20*%20To%20view%20and%20modify%20this%20theme%2C%20visit%20http%3A%2F%2Fjqueryui.com%2Fthemeroller%2F%5Cn%20*%2F%5Cnh1%20%7B%5Cn%20%20font-size%3A%202em%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%221.27.0%22%7D)

**Comment by mcabansag** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by devongovett** [comment]
It will retain multiple but only if you put the license comments at the top, before any other rules.
