### ISSUE TITLE
cannot add `@media (color-gamut: p3)` for p3 colors

### ISSUE THREAD

**Issue by jjenzz** [parcel-bundler/lightningcss#833]
lightning css will wrap a `@supports` check around p3 colors and provide fallbacks but does not ensure that the display is a p3 display. i tried wrapping the media query myself but it wraps the fallback that lightning css generates too:

[![CleanShot 2024-10-13 at 14 31 30](https://github.com/user-attachments/assets/671bafdb-db30-43cd-a081-205b0dcf0232)](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%40media%20(color-gamut%3A%20p3)%20%7B%5Cn%20%20%3Aroot%20%7B%5Cn%20%20%20%20--color_violet10%3A%20color(display-p3%200.381%200.306%200.741)%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)
_click image for playground_

it looks like i can disable `Features.ColorFunction` and `Features.P3Colors` and then folks can manually add the styles they need for now but if i ever need to reenable these features, it bloats the CSS a bit:

[![CleanShot 2024-10-13 at 15 18 49](https://github.com/user-attachments/assets/ec58ca53-6cd1-41ba-a8ee-dc5f288726ba)](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%5Bdata-theme%3D'light'%5D%20%7B%5Cn%20%20--color_violet10%3A%20%23654dc4%3B%5Cn%20%20--color_violet11%3A%20%236550b9%3B%5Cn%20%20--color_violet9%3A%20%236e56cf%3B%5Cn%7D%5Cn%5Cn%5Bdata-theme%3D'dark'%5D%20%7B%5Cn%20%20--color_violet10%3A%20%237d66d9%3B%5Cn%20%20--color_violet11%3A%20%23baa7ff%3B%5Cn%20%20--color_violet9%3A%20%236e56cf%3B%5Cn%7D%5Cn%5Cn%40media%20(color-gamut%3A%20p3)%20%7B%5Cn%20%20%40supports%20(color%3A%20color(display-p3%201%201%201))%20%7B%5Cn%20%20%20%20%5Bdata-theme%3D'light'%5D%20%7B%5Cn%20%20%20%20%20%20--color_violet10%3A%20color(display-p3%200.381%200.306%200.741)%3B%5Cn%20%20%20%20%20%20--color_violet11%3A%20color(display-p3%200.383%200.317%200.702)%3B%5Cn%20%20%20%20%20%20--color_violet9%3A%20color(display-p3%200.417%200.341%200.784)%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%40media%20(color-gamut%3A%20p3)%20%7B%5Cn%20%20%40supports%20(color%3A%20color(display-p3%201%201%201))%20%7B%5Cn%20%20%20%20%5Bdata-theme%3D'dark'%5D%20%7B%5Cn%20%20%20%20%20%20--color_violet10%3A%20color(display-p3%200.477%200.402%200.823)%3B%5Cn%20%20%20%20%20%20--color_violet11%3A%20color(display-p3%200.72%200.65%201)%3B%5Cn%20%20%20%20%20%20--color_violet9%3A%20color(display-p3%200.417%200.341%200.784)%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

**Comment by mcabansag** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by devongovett** [comment]
Not sure I understand the issue here. Lightning CSS only checks whether the color value is supported (i.e. parses), not whether the display can support that color. Browsers that support P3 colors should automatically generate an equivalent sRGB color at render time for non-supporting output devices. I don't think you need to include the check for `@media (color-gamut: p3)` at all if you want the same color values on P3 and sRGB displays. If you want different colors than you would need it, but Lightning CSS can't help with that anyway.

**Comment by jjenzz** [comment]
this arose from a rabbit hole i ended up in when i tried to use Radix Colors because the fallback colours they provide are not the same hex codes that lightning generates. in order to match Radix exactly, i tried to define my own fallbacks and match the `@media (color-gamut: p3)` query they use in Radix Themes but it all went a bit south 😅  

even without the media query, it still gets [a bit messy when defining my own fallbacks](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%5Bdata-theme%3D'light'%5D%20%7B%5Cn%20%20--color_violet10%3A%20%23654dc4%3B%5Cn%20%20--color_violet11%3A%20%236550b9%3B%5Cn%20%20--color_violet9%3A%20%236e56cf%3B%5Cn%7D%5Cn%5Cn%5Bdata-theme%3D'dark'%5D%20%7B%5Cn%20%20--color_violet10%3A%20%237d66d9%3B%5Cn%20%20--color_violet11%3A%20%23baa7ff%3B%5Cn%20%20--color_violet9%3A%20%236e56cf%3B%5Cn%7D%5Cn%5Cn%40supports%20(color%3A%20color(display-p3%201%201%201))%20%7B%5Cn%20%20%5Bdata-theme%3D'light'%5D%20%7B%5Cn%20%20%20%20--color_violet10%3A%20color(display-p3%200.381%200.306%200.741)%3B%5Cn%20%20%20%20--color_violet11%3A%20color(display-p3%200.383%200.317%200.702)%3B%5Cn%20%20%20%20--color_violet9%3A%20color(display-p3%200.417%200.341%200.784)%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%40supports%20(color%3A%20color(display-p3%201%201%201))%20%7B%5Cn%20%20%5Bdata-theme%3D'dark'%5D%20%7B%5Cn%20%20%20%20--color_violet10%3A%20color(display-p3%200.477%200.402%200.823)%3B%5Cn%20%20%20%20--color_violet11%3A%20color(display-p3%200.72%200.65%201)%3B%5Cn%20%20%20%20--color_violet9%3A%20color(display-p3%200.417%200.341%200.784)%3B%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D) but tbh, the difference between Radix fallbacks and lightningcss ones doesn't appear to be noticeable, so i ended up letting lightningcss handle it all in the end.

i'll close this but happy to open a separate ticket for the fallbacks issue if you think it warrants some attention. i'm not so sure tho.
