### ISSUE TITLE
Incorrect reduction of `clamp` to `min` given a negative bound

### ISSUE THREAD

**Issue by alcore** [parcel-bundler/lightningcss#836]
Given the following...

```
margin: 100px clamp(-100px, 0px, 50% - 50vw)
```

... to set a negative horizontal margin when sufficient space is available in the container and viewport, while making sure it doesn't extrude more than 100px outwards (min of -100px) and does not get a positive margin inwards (max of 0px) from the dynamic calc.

LightningCSS (1.27) reduces that to:

```
margin: 100px min(0px, 50% - 50vw)
```

It gets correctly retained when the math is expressed by its equivalent instead:

```
margin: 100px max(-100px, min(0px, 50% - 50vw))
```

**Comment by mcabansag** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
