### ISSUE TITLE
Stackoverflow at add_recursive in percentage.rs:288

### ISSUE THREAD

**Issue by DrSloth** [parcel-bundler/lightningcss#845]
I am encountering a stackoverflow when using lightningcss. I can not yet pin down what input exactly creates this but it would be nice if this kind of lowering in minification could be disabled.

The problem occurs when calling Stylesheet::parse.

Thanks for your work and have a nice day.

**Comment by mcabansag** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by DrSloth** [comment]
Nice try bro. Never underestimate the infinite power of the not using windows.

**Comment by devongovett** [comment]
Fixed several issues related to this just now. Hopefully this fixed your case. But I'd need a reproduction to verify.
