### ISSUE TITLE
"Error: lightningcss-android-arm64 not found"
termux on Device: android  
Architecture: aarch64

### ISSUE THREAD

**Issue by PriyanshSinghBisht** [parcel-bundler/lightningcss#851]
steps to re-create issue:

1. npx create-expo-app
2. npm run reset-project
3. setup nativewind v4 according to doc ( in expo router setup section) here is link :- []()https://www.nativewind.dev/getting-started/expo-router

4. run the project with command. 
       npx expo start

![Screenshot_2024-11-06-11-13-11-465_com.termux.jpg](https://github.com/user-attachments/assets/d444899d-a753-4423-9635-494f0694ddc5)

![Screenshot_2024-11-06-11-07-22-953_com.foxdebug.acode.jpg](https://github.com/user-attachments/assets/6c034c91-e8e5-4927-849a-b8dc61f9b346)

I think error occured from this file.

**Comment by robertmunceanu** [comment]
I am having the same issue. @PriyanshSinghBisht did you manage to fix this?

**Comment by PriyanshSinghBisht** [comment]
Sorry for the delayed response. I was busy.

Regarding the issue, I have not been able to resolve it yet. However, I reached out to [remo773](https://www.reddit.com/user/remo773/) for assistance. He cloned the official LightningCSS repository and built the lightningcss-android-arm64 file using Android NDK and Rust within the Termux app.

He has published the compiled file [here](https://github.com/remo7777/REMO773/blob/master/lightningcss.aarch64.tar.gz). To use it, simply place the extracted contents in the node_modules/lightningcss/ directory, as the file is compressed and needs to be extracted first.

[https://www.reddit.com/r/termux/comments/1gmf5a0/node_module_lightningcss1280/?show=original](https://www.reddit.com/r/termux/comments/1gmf5a0/node_module_lightningcss1280/?show=original) you can see his reddit post for this topic here.

Let me know if you need any further details!
