### ISSUE TITLE
`&_title` selector not working as expected

### ISSUE THREAD

**Issue by olivierbossel** [parcel-bundler/lightningcss#852]
Hi there!

I've tried to use this kind of css selector that works in `scss` and that is very useful, but it does not work for now.

```css
.header {
    /* ... */

    &_title {
        /* ... */
    }
}
```

Here's the expected output:

```css
.header .header_title {
   /* ... */
}
```

And here's what generated for now:

```css
_title.header {
   /* ... */
}
```

Is that something that is by design not supported or can this be "fixed"?

I'm on version `1.28.1`

Many thanks in advance!

Best regards

**Comment by devongovett** [comment]
That's not how nesting in CSS works. Maybe you're thinking of SASS?
