### ISSUE TITLE
Support multiple files with CLI

### ISSUE THREAD

**Issue by benoitchantre** [parcel-bundler/lightningcss#90]
Would it be possible to support multiple files as input / output using the CLI?

PostCSS and ESbuild allow to use a glob pattern for the input and have arguments to set the output directory and extension.

Examples:
- `postcss src/**/*.css --base src --dir dist/css --ext .min.css `
- `esbuild src/**/*.js --bundle --outdir=dist/JS --out-extension:.js=.min.js`

A similar solution would be very useful as many projects have more than one stylesheet.

**Comment by devongovett** [comment]
Yep, this would be a nice feature. 👍

**Comment by mrkldshv** [comment]
Hey! I'd like to take a stab at this issue. Do we want to use any crate for glob pattern?

**Comment by mryechkin** [comment]
Would love to see this!

**Comment by makkabi** [comment]
+1, I tried to replace postcss with lightningcss, but I'm missing three things: 1. Support for browserslist in package-json (use --target instead) 2. No built-in watch-mode (I use the onchange package for this) and 3. this (handle all css files in a folder), and this is what prevents me using lightningcss-cli for now, because the only workaround I see is one npm script for every css file, and that is hard du manually manage and will bloat the package.json file.

**Comment by devongovett** [comment]
In the meantime, you can use bash scripting or something like the `find` command to process multiple files:

```bash
 find . -name '*.css' -exec lightningcss {} -o dist/{} \;
```

**Comment by makkabi** [comment]
> In the meantime, you can use bash scripting or something like the `find` command to process multiple files:
> 
> ```shell
>  find . -name '*.css' -exec lightningcss {} -o dist/{} \;
> ```

Thanks! If I would really need it, I would try it, but for now I just stick to PostCSS. Btw., I saw that (as of now) other developers just assume that *.css works: [11ty-Sass-Skeleton by @5t3ph](https://github.com/5t3ph/11ty-sass-skeleton/commit/16d8a06838c2f46dedf15be971d2a229dc216a82)
(And it does work - until you have more than one css file...)

**Comment by devongovett** [comment]
that's fine, but just wanted to point out that this is possible since your original comment implied that it was not:

> this is what prevents me using lightningcss-cli for now

**Comment by LeoniePhiline** [comment]
@mrkldshv Are you still working on this?

**Comment by mrkldshv** [comment]
Nope, feel free to take it!

**Comment by LeoniePhiline** [comment]
Unfortunately I also won't manage currently to work on this. Free to take!

**Comment by benoitchantre** [comment]
> In the meantime, you can use bash scripting or something like the `find` command to process multiple files:
> 
> ```shell
>  find . -name '*.css' -exec lightningcss {} -o dist/{} \;
> ```

@devongovett I did some tests without success. After having adjusted the path (before `-name`) to search in the source files only, the output file coming from `{}` need be rewritten in order to suppress the source directory. I haven’t found a solution for that.

I would love to see some move for a native support of this feature. Is it something in your roadmap?

**Comment by benoitchantre** [comment]
Here's a workaround to get the output files in the expected directories.

```
find assets/css/ -type d -exec bash -c 'mkdir -p dist/${0#assets/}' {} \; && find assets/css/ -type f -name '[^_]*.css' -exec bash -c 'lightningcss --minify --bundle --browserslist $0 --output-file dist/${0#assets/}' {} \;
```

Notes :
- The directories have to be created before to run lightningcss prevent a *No such file or directory* erroor
-  I haven't found a way to rename the file extension (ex: `.css` to `.min.css`)

**Comment by pepicrft** [comment]
I tried to use the added support for globs in the input arguments, and I'm facing the following error:

```bash
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

This is the command that I'm invoking:
```bash
lightning_css lib/glossia_web/** --bundle --output-file=priv/static/assets/app.css
```

Do you know what might be the issue?
